Repository Azure/azure-cli, pull requests merged in 2019-11, with the labels that each got.

#10955 Fix #10578: `az login` hangs
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/util.py
  src/azure-cli/HISTORY.rst
Labels: Do Not Merge

#11169 [CI] Lock azure-mgmt-appconfig version to 0.2.0 and Upgrade pywin32 to 225, cryptography to 2.8 to support Python 3.8
  src/azure-cli/requirements.py2.Darwin.txt
  src/azure-cli/requirements.py2.Linux.txt
  src/azure-cli/requirements.py2.windows.txt
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: CI, External Dependency

#11126 [Reservations] Upgrade SDK to version 0.6.0
  src/azure-cli/HISTORY.rst
  src/azure-cli/azure/cli/command_modules/reservations/_client_factory.py
  src/azure-cli/azure/cli/command_modules/reservations/commands.py
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_get_applied_reservation_order_ids.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_get_catalog.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_get_reservation.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_get_reservation_order.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_list_reservation.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_list_reservation_history.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_list_reservation_order.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_split_and_merge.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/recordings/test_update_reservation.yaml
  src/azure-cli/azure/cli/command_modules/reservations/tests/latest/test_reservations_commands.py
  src/azure-cli/requirements.py2.Darwin.txt
  src/azure-cli/requirements.py2.Linux.txt
  src/azure-cli/requirements.py2.windows.txt
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Service Attention

#11040 App Service Environment commands
  src/azure-cli/HISTORY.rst
  src/azure-cli/azure/cli/command_modules/appservice/_help.py
  src/azure-cli/azure/cli/command_modules/appservice/_params.py
  src/azure-cli/azure/cli/command_modules/appservice/_validators.py
  src/azure-cli/azure/cli/command_modules/appservice/appservice_environment.py
  src/azure-cli/azure/cli/command_modules/appservice/commands.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_app_service_environment_list_rg.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py
Labels: App Services
