Repository Azure/azure-cli, pull requests merged in 2020-12, with the labels that each got.

#15933 [APIM] az apim restore: New command to restore a backup of an API Management service
  src/azure-cli/azure/cli/command_modules/apim/_help.py
  src/azure-cli/azure/cli/command_modules/apim/_params.py
  src/azure-cli/azure/cli/command_modules/apim/commands.py
  src/azure-cli/azure/cli/command_modules/apim/custom.py
Labels: customer-reported

#16097 {CI} Pin pip==20.2.4 and fix CredScan upgrade
  azure-pipelines.yml
  scripts/ci/credscan/CredScanSuppressions.json
Labels: CI

#15963 {Error Improvement} Error category and error message refining
  src/azure-cli-core/azure/cli/core/azclierror.py
  src/azure-cli-core/azure/cli/core/util.py
Labels: Error Handling

#15958 {Compute} Update shared image gallery scenarios
  src/azure-cli/azure/cli/command_modules/vm/_help.py
Labels: Compute

#16011 [AKS ] az aks get-credentials: Clarify documentation for get-credentials
  src/azure-cli/azure/cli/command_modules/acs/_help.py
Labels: AKS

#15901 {Core} Honor expiresOn, instead of expiresIn
  src/azure-cli-core/azure/cli/core/adal_authentication.py
  src/azure-cli-core/azure/cli/core/tests/test_adal_authentication.py
Labels: Track2

#16110 {Error Improvement} Use short link in error reference
  src/azure-cli-core/azure/cli/core/parser.py
  src/azure-cli-core/azure/cli/core/util.py
Labels: Error Handling

#16012 [Compute] New license type RHEL_ELS_6
  src/azure-cli/azure/cli/command_modules/vm/_params.py
Labels: Compute

#16190 {CI} Enable --no-exitfirst for automation test in CI
  .azure-pipelines/templates/automation_test.yml
Labels: CI

#16198 [Security] - Add secure score commands
  src/azure-cli/azure/cli/command_modules/security/_client_factory.py
  src/azure-cli/azure/cli/command_modules/security/_help.py
  src/azure-cli/azure/cli/command_modules/security/_params.py
  src/azure-cli/azure/cli/command_modules/security/commands.py
  src/azure-cli/azure/cli/command_modules/security/custom.py
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_allowed_connections.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_assessments.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_atp_settings.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_auto_provisioning_setting.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_compliance.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_contacts.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_discovered_security_solutions.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_external_security_solutions.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_iot.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_jit_policy.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_locations.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_pricings.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_secure_score.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_settings.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_tasks.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_topology.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/recordings/test_security_workspace_settings.yaml
  src/azure-cli/azure/cli/command_modules/security/tests/latest/test_secure_score_scenario.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Security

#16213 [ARO] az aro update: Add RBAC validation on cluster update
  src/azure-cli/azure/cli/command_modules/aro/_help.py
  src/azure-cli/azure/cli/command_modules/aro/_rbac.py
  src/azure-cli/azure/cli/command_modules/aro/_validators.py
  src/azure-cli/azure/cli/command_modules/aro/custom.py
  src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_create.yaml
  src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_delete.yaml
  src/azure-cli/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_update.yaml
Labels: ARO

#16255 [Monitor] az monitor metrics alert create: improve error message to give more actionable insight
  src/azure-cli/azure/cli/command_modules/monitor/actions.py
Labels: Monitor - Alerts

#16240 {Misc} Update local context doc for new name param persist
  doc/parampersist_localcontext_guidelines.md
Labels: Local Context

#16299 {Monitor} Fix monitor test 7/7
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_for_rg_and_sub.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_vm_metric_alerts_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_data_export.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_private_link_scope.py
Labels: Monitor

#16315 {Network} Fix live test
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_webapp.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Labels: Network, Test

#16327 {Storage} fix help
  src/azure-cli/azure/cli/command_modules/storage/_help.py
Labels: Help, Storage

#16302 {Packaging} Fix version to conform to pip 20.3
  azure-pipelines-full-tests.yml
  azure-pipelines.yml
  scripts/ci/build.sh
  scripts/ci/version.sh
  scripts/release/pypi/build.sh
Labels: Packaging

#16296 [AppService] Unhide Python 3.9 in functionapp create
  src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
Labels: App Services

#16332 {Telemetry} Reomve trace stack info in Telemetry
  src/azure-cli-core/azure/cli/core/telemetry.py
Labels: Error Handling

#16273 {Error Handling} Show explicit error messages for HttpOperationError
  src/azure-cli-core/azure/cli/core/util.py
Labels: Error Handling

#16252 {Doc} Fix spelling (mySubscrpitionId)
  src/azure-cli/azure/cli/command_modules/container/_help.py
Labels: customer-reported

#16309 [ARO] Ensure worker_profile is not None before getting the subnets from
  src/azure-cli/azure/cli/command_modules/aro/custom.py
Labels: ARO

#15975 [ACR] bump api version. support zone redundancy
  src/azure-cli-core/azure/cli/core/profiles/_shared.py
  src/azure-cli/azure/cli/command_modules/acr/_client_factory.py
  src/azure-cli/azure/cli/command_modules/acr/_params.py
  src/azure-cli/azure/cli/command_modules/acr/custom.py
  src/azure-cli/azure/cli/command_modules/acr/replication.py
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_agentpool.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_replication.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_webhook.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_with_audits.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_with_managed_registry.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_encryption_with_cmk.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_identity.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_image_import.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_network_rule.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_task.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_taskrun.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_dedicated_data_endpoints.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_private_endpoint.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_public_network_access.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_zone_redundancy.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_check_name_availability.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_repository_token_create.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_create_function_app.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_deployment_function_app.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration_function_app.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_acr.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_acr.yaml
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_tag_update_by_patch.yaml
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Container Registry

#16238 [ACR] az acr connected-acr create/update/delete/list/show: new feature in beta.
  src/azure-cli/azure/cli/command_modules/acr/_client_factory.py
  src/azure-cli/azure/cli/command_modules/acr/_format.py
  src/azure-cli/azure/cli/command_modules/acr/_help.py
  src/azure-cli/azure/cli/command_modules/acr/_params.py
  src/azure-cli/azure/cli/command_modules/acr/_utils.py
  src/azure-cli/azure/cli/command_modules/acr/commands.py
  src/azure-cli/azure/cli/command_modules/acr/connected_registry.py
  src/azure-cli/azure/cli/command_modules/acr/scope_map.py
  src/azure-cli/azure/cli/command_modules/acr/token.py
Labels: Container Registry

#15502 [ARM] `az deployment`: Fix parse errors with multiline strings
  src/azure-cli-core/azure/cli/core/util.py
  src/azure-cli/azure/cli/command_modules/resource/custom.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/recordings/test_resource_group_deployment.yaml
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/simple_deploy_multiline.json
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Labels: customer-reported

#16389 {AKS} Fix typo: satsify -> satisfy
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: customer-reported

#14690 {Identity} Identity new features
  azure-cli.pyproj
  azure-cli2017.pyproj
  scripts/ci/dependency_check.sh
  scripts/install_full.sh
  scripts/release/debian/Dockerfile
  scripts/release/debian/build.sh
  scripts/release/debian/prepare.sh
  scripts/release/rpm/Dockerfile.centos
  scripts/release/rpm/Dockerfile.fedora
  scripts/release/rpm/azure-cli.spec
  scripts/release/rpm/build.sh
  src/azure-cli-core/azure/cli/core/_debug.py
  src/azure-cli-core/azure/cli/core/_identity.py
  src/azure-cli-core/azure/cli/core/_msal.py
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/adal_authentication.py
  src/azure-cli-core/azure/cli/core/commands/client_factory.py
  src/azure-cli-core/azure/cli/core/credential.py
  src/azure-cli-core/azure/cli/core/profiles/_shared.py
  src/azure-cli-core/azure/cli/core/tests/test_adal_authentication.py
  src/azure-cli-core/azure/cli/core/tests/test_identity.py
  src/azure-cli-core/azure/cli/core/tests/test_profile.py
  src/azure-cli-core/azure/cli/core/tests/test_profile_v2016_06_01.py
  src/azure-cli-core/setup.py
  src/azure-cli-testsdk/azure/cli/testsdk/patches.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_app_service_environment_commands_thru_mock.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands_thru_mock.py
  src/azure-cli/azure/cli/command_modules/configure/_consts.py
  src/azure-cli/azure/cli/command_modules/configure/custom.py
  src/azure-cli/azure/cli/command_modules/keyvault/_completers.py
  src/azure-cli/azure/cli/command_modules/profile/__init__.py
  src/azure-cli/azure/cli/command_modules/profile/_help.py
  src/azure-cli/azure/cli/command_modules/profile/custom.py
  src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
  src/azure-cli/azure/cli/command_modules/role/custom.py
  src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
  src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/requirements.opt.py3.Linux.txt
  src/azure-cli/requirements.opt.py3.Trusty.txt
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
Labels: Azure Identity Integration
