Repository Azure/azure-cli, pull requests merged in 2020-01, with the labels that each got.

#11776 fix: az monitor metric alert create. Fix test failure.
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_metric_alert_v2_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_metric_alert_scenarios.py
Labels: Monitor

#11802 Fix: tox can find system-wide default Python 2.7 in ADO
  azure-pipelines.yml
Labels: CI

#11815 Chore: move CredScansuppressions.json to codeownder guarded folder
  azure-pipelines.yml
  scripts/ci/credscan/CredScanSuppressions.json
Labels: CI

#11844 Chore: disable CredScan job temporary for ADO security concern
  azure-pipelines.yml
Labels: CI

#11847 refact: update global --tags help content
  src/azure-cli-core/azure/cli/core/commands/parameters.py
Labels: Core, Documentation

#11649 [Storage]: Add a new command group `az storage share-rm` to use the Microsoft.Storage resource provider for Azure file share management operations.
  src/azure-cli/HISTORY.rst
  src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
  src/azure-cli/azure/cli/command_modules/storage/_help.py
  src/azure-cli/azure/cli/command_modules/storage/_params.py
  src/azure-cli/azure/cli/command_modules/storage/_validators.py
  src/azure-cli/azure/cli/command_modules/storage/commands.py
  src/azure-cli/azure/cli/command_modules/storage/operations/file.py
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_using_rm_main_scenario.yaml
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_using_resource_provider_scenarios.py
Labels: Storage

#11794 [IoT] Deprecated command group 'iot hub job'
  src/azure-cli/HISTORY.rst
  src/azure-cli/azure/cli/command_modules/iot/commands.py
Labels: Do Not Merge

#11798 [Core][Profile] Add `tenant` parameter to `get_raw_token`
  src/azure-cli-core/HISTORY.rst
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/tests/test_profile.py
  src/azure-cli/HISTORY.rst
  src/azure-cli/azure/cli/command_modules/profile/__init__.py
  src/azure-cli/azure/cli/command_modules/profile/_help.py
  src/azure-cli/azure/cli/command_modules/profile/custom.py
  src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
Labels: Do Not Merge
