Repository Azure/azure-cli, pull requests merged in 2020-08, with the labels that each got.

#14622 {CI} replace 2019-07-01 with 2020-06-01
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_assign_user_identity.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_create_with_msi.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_remove_identity.yaml
Labels: Do Not Merge

#14554 [AppConfig] Support enabling/disabling PublicNetworkAccess during store creation
  scripts/ci/credscan/CredScanSuppressions.json
  src/azure-cli/azure/cli/command_modules/appconfig/_help.py
  src/azure-cli/azure/cli/command_modules/appconfig/_params.py
  src/azure-cli/azure/cli/command_modules/appconfig/custom.py
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_public_network_access.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
Labels: App Configuration

#13486 [Lab] Fix for issue #7904 date validation bug in lab vm creation
  src/azure-cli/azure/cli/command_modules/lab/validators.py
Labels: Compute

#14624 [Compute] Support associating disk and snapshot with a disk-access resource
  src/azure-cli-core/azure/cli/core/profiles/_shared.py
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_snapshot.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_template_outputs.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_specialized_image.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_by_attach_os_and_data_disks.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_with_standard_zrs_sku.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_incremental.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute

#14717 [AKS] Remove preview tag from Virtual Node add-on
  src/azure-cli/azure/cli/command_modules/acs/_help.py
Labels: AKS

#14619 [Backup] Added VM tests
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_container.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_disk_exclusion.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_item.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_job.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_policy.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_protection.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_restore.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_rp.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_scenario.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_softdelete.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
Labels: Recovery Services Backup, Test

#14668 [RBAC] az ad group create: support specify description when creating a group
  src/azure-cli/azure/cli/command_modules/role/_params.py
  src/azure-cli/azure/cli/command_modules/role/custom.py
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_graph_group_scenario.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
Labels: RBAC

#14688 [AKS] add AKS CMK argument in cluster creation
  linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: AKS

#14640 [RBAC] BREAKING CHANGE: az ad sp create-for-rbac: change default permission of created certificate
  src/azure-cli/azure/cli/command_modules/role/_help.py
  src/azure-cli/azure/cli/command_modules/role/custom.py
Labels: AAD

#14685 [Compute] image builder create: Add --vm-size, --os-disk-size, --vnet, --subnet
  src/azure-cli/azure/cli/command_modules/vm/_image_builder.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_builder_basic.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_image_builder_commands.py
Labels: Compute

#14757 {KeyVault} Fix the bad link
  src/azure-cli/azure/cli/command_modules/keyvault/_help.py
Labels: KeyVault

#14808 [Compute] New command az vm assess-patches
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_auto_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute

#14752 {KeyVault} Add deprecation messages for soft-delete related commands and parameters
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
  src/azure-cli/azure/cli/command_modules/keyvault/commands.py
Labels: KeyVault

#14803 [Upgrade] Add `az upgrade` command
  src/azure-cli-core/azure/cli/core/__init__.py
  src/azure-cli-core/azure/cli/core/extension/_resolve.py
  src/azure-cli-core/azure/cli/core/extension/operations.py
  src/azure-cli-core/azure/cli/core/extension/tests/latest/test_extension_commands.py
  src/azure-cli-core/azure/cli/core/telemetry.py
  src/azure-cli-core/azure/cli/core/util.py
  src/azure-cli/azure/cli/__main__.py
  src/azure-cli/azure/cli/command_modules/extension/__init__.py
  src/azure-cli/azure/cli/command_modules/extension/_help.py
  src/azure-cli/azure/cli/command_modules/extension/custom.py
  src/azure-cli/azure/cli/command_modules/util/_help.py
  src/azure-cli/azure/cli/command_modules/util/_params.py
  src/azure-cli/azure/cli/command_modules/util/commands.py
  src/azure-cli/azure/cli/command_modules/util/custom.py
Labels: Packaging

#14150 {KeyVault} Track 2 mgmt-plane adoption
  scripts/sdk_process/patch_models.py
  src/azure-cli-core/azure/cli/core/commands/arm.py
  src/azure-cli-core/azure/cli/core/profiles/__init__.py
  src/azure-cli/azure/cli/command_modules/keyvault/_command_type.py
  src/azure-cli/azure/cli/command_modules/keyvault/_help.py
  src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
  src/azure-cli/azure/cli/command_modules/keyvault/commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_certificate_contacts.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_certificate_crud.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_certificate_download.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_certificate_get_default_policy.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_certificate_import.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_certificate_issuers.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_key.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_pending_certificate.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_secret.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/recordings/test_keyvault_softdelete.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2018_03_01/test_keyvault_commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/cert_secret
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/policy3.json
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_contacts.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_crud.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_download.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_import.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_certificate_issuers.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key_download.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_network_rule.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_pending_certificate.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_private_endpoint_connection.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_private_link_resource.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_secret_soft_delete.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_softdelete.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: KeyVault, Track2

#14836 {Core} Add endpoint and suffix for attestation
  src/azure-cli-core/azure/cli/core/cloud.py
Labels: Cloud

#14797 {Storage} `az storage container`: Fix language in logging.warning call
  src/azure-cli/azure/cli/command_modules/storage/_validators.py
  src/azure-cli/azure/cli/command_modules/storage/_validators_azure_stack.py
Labels: Do Not Merge

#14900 {Test} Add gcc in deb test script
  scripts/release/debian/test_deb_in_docker.sh
Labels: Test

#14874 [Network] BREAKING CHANGE: Allow to create both public and private IP while creating an Application Gateway
  src/azure-cli/azure/cli/command_modules/network/_params.py
  src/azure-cli/azure/cli/command_modules/network/_template_builder.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_appgw_creation_with_public_and_private_ip.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network - Application Gateway

#14922 [Network] Fix help message of options about connection-monitor endpoint
  src/azure-cli/azure/cli/command_modules/network/_params.py
Labels: Network - Network Watcher

#14905 {Core} Stop importing pkg_resources when getting versions
  src/azure-cli-core/azure/cli/core/util.py
  src/azure-cli-telemetry/azure/cli/telemetry/__init__.py
  src/azure-cli/azure/cli/command_modules/util/tests/latest/test_version.py
Labels: Performance

#14952 [ACR] Add Isolated Tier to Agent Pool
  src/azure-cli/azure/cli/command_modules/acr/_params.py
Labels: Container Registry

#14576 [ACR] Add OCI Artifact Source Context
  src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
  src/azure-cli/azure/cli/command_modules/acr/_help.py
  src/azure-cli/azure/cli/command_modules/acr/_params.py
  src/azure-cli/azure/cli/command_modules/acr/task.py
Labels: Container Registry

#14974 {Doc} doc/try_new_features_before_release.md
  doc/try_new_features_before_release.md
Labels: Documentation
