Repository Azure/azure-cli, pull requests merged in 2021-03, with the labels that each got.

#17091 {Packaging} Upgrade pip version in bundled Python
  build_scripts/windows/scripts/build.cmd
  scripts/release/debian/build.sh
Labels: Packaging

#17073 [Style] Allow configuring theme
  src/azure-cli-core/azure/cli/core/__init__.py
  src/azure-cli/azure/cli/command_modules/util/_params.py
  src/azure-cli/azure/cli/command_modules/util/custom.py
Labels: style

#17157 {AppConfig} Remove preview tags for some commands
  src/azure-cli/azure/cli/command_modules/appconfig/_params.py
  src/azure-cli/azure/cli/command_modules/appconfig/commands.py
Labels: App Configuration

#17054 [AppService]: fix #17053- `az webapp show` returning null values for SiteConfig properties
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_deploy_zip.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_download_win_web_log.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_ragrs_storage_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_local_context.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_multicontainer_create.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_linux_webapp_remote_ssh.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_hybridconnectionE2E.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_list_deployment_logs.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_local_context.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_show_deployment_logs.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import_crossrg.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: App Services

#17165 [BACKUP] Added id_part for sub-resource names
  src/azure-cli/azure/cli/command_modules/backup/_help.py
  src/azure-cli/azure/cli/command_modules/backup/_params.py
  src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
Labels: Recovery Services Backup

#17119 [Keyvault] `az keyvault role definition list`: Support `--custom-role-only` to list only custom role definitions
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Labels: KeyVault

#17113 {Keyvault} Fix #17040: Support `--id` to specify URL of HSM in command `az keyvault security-domain download`
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Labels: KeyVault

#17183 [BACKUP] Fix #17094: Created separate test suite for CRR tests
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_crr.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_restore.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
Labels: Recovery Services Backup

#16974 [BACKUP] az backup protection check-vm: Add vm and resource-group as optional params
  src/azure-cli/azure/cli/command_modules/backup/_params.py
  src/azure-cli/azure/cli/command_modules/backup/custom.py
  src/azure-cli/azure/cli/command_modules/backup/custom_base.py
Labels: Recovery Services Backup

#17109 [Keyvault] Support keyvault custom role definition
  src/azure-cli/azure/cli/command_modules/keyvault/_help.py
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
  src/azure-cli/azure/cli/command_modules/keyvault/commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_role_definition.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Labels: KeyVault

#17178 {Packaging} Upgrade pip version in RPM
  scripts/release/rpm/azure-cli.spec
Labels: Packaging/Pip, customer-reported

#17192 [AKS] Add --no-uptime-sla
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: AKS

#17115 [acr] output a trace in "az acr login" for self-diagnosing potential docker command latency
  src/azure-cli/azure/cli/command_modules/acr/custom.py
Labels: Container Registry

#17177 [acr] fix a bug when run check-health behind corporate proxy
  src/azure-cli/azure/cli/command_modules/acr/check_health.py
Labels: Recovery Services Backup

#17190 [Service Fabric] az sf certificate: deprecate cluster cert commands
  src/azure-cli/azure/cli/command_modules/servicefabric/commands.py
  src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
  src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_cluster_certs.yaml
  src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_cluster.py
Labels: Service Fabric

#17006 [acr] support anonymous pull
  src/azure-cli/azure/cli/command_modules/acr/_params.py
  src/azure-cli/azure/cli/command_modules/acr/custom.py
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_replication.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_webhook.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_task.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_with_anonymous_pull.yaml
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Container Registry

#17255 [VM] Add #16037: az vm open-port accepts list of ports
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_open_port.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute - VM

#17259 [AppService]: fix #17207 - for az webapp log config 'level' always defaults to verbose
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
Labels: App Services

#17274 [Compute] Fix #16585: az vmss deallocate --instance-ids failed
  src/azure-cli/azure/cli/command_modules/vm/custom.py
Labels: Compute

#16409 [Compute] az vm create: New parameter `--platform-fault-domain` in FLEX VMSS mode
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_linux_vm_patch_mode.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_auto_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_orchestration_mode.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute

#17281 [AKS] Fix cross-sub assigning identity error and attach acr error
  src/azure-cli/azure/cli/command_modules/acs/_client_factory.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: AKS

#17305 {Doc} Add instructions to write and run commands in VS Code with the Azure CLI Tool
  README.md
Labels: Documentation

#17138 [AKS] Add support for node public IP prefix ID
  linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: AKS

#17320 {Compute} Update describe for 'azure/cli/command_modules/vm/_help.py'
  src/azure-cli/azure/cli/command_modules/vm/_help.py
Labels: customer-reported

#17263 [KeyVault] Add `--no-wait` for command `az keyvault security-domain download` and `--target-operation` for command `az keyvault security-domain wait`
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
  src/azure-cli/azure/cli/command_modules/keyvault/commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_t1/v7_2/key_vault_client.py
Labels: KeyVault

#17317 {Packaging} Remove aio and dist-info folders in MSI
  azure-pipelines.yml
  build_scripts/windows/scripts/build.cmd
Labels: Packaging

#17299 [ACR] Fix#16700: Use "exists" api to check storage blob existence
  src/azure-cli/azure/cli/command_modules/acr/_stream_utils.py
Labels: Container Registry

#17217 [Compute] vm create: New parameter --count
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/_validators.py
  src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_count.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute

#17301 {Feedback} Fix feedback minification
  src/azure-cli/azure/cli/command_modules/feedback/custom.py
Labels: customer-reported

#17354 [Compute] vm create: Trusted Launch
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute

#17356 {Misc.} Bump marketplaceordering sdk to Track2
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_image_terms.yaml
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Marketplace Ordering

#16957 [BACKUP] Fix #14776: Fix --force parameter functionality for az backup vault delete command
  .github/CODEOWNERS
  src/azure-cli/azure/cli/command_modules/backup/custom.py
Labels: Recovery Services Backup

#17367 [backup] Fix on demand backup
  src/azure-cli/azure/cli/command_modules/backup/_params.py
  src/azure-cli/azure/cli/command_modules/backup/custom.py
  src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
  src/azure-cli/azure/cli/command_modules/backup/custom_base.py
  src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
Labels: Recovery Services Backup

#17463 {pipeline} Update azdev_setup.yml
  .azure-pipelines/templates/azdev_setup.yml
Labels: customer-reported

#17414 [backup] Optional parameter 'backup-management-type' in 'backup protectable-item list' command
  src/azure-cli/azure/cli/command_modules/backup/_help.py
  src/azure-cli/azure/cli/command_modules/backup/_params.py
  src/azure-cli/azure/cli/command_modules/backup/custom_base.py
  src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
Labels: Recovery Services Backup

#17380 [ARM] Fix #17379: bicep auto install results in invalid json output from deployment
  src/azure-cli/azure/cli/command_modules/resource/_bicep.py
Labels: customer-reported

#17479 [AppService] Fixes #17219: Fix ssl bind bug
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
Labels: App Services

#17430 [AKS] az aks create: add support for --private-dns-zone and --fqdn-subdomain feature
  src/azure-cli/azure/cli/command_modules/acs/_consts.py
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_create_fqdn_subdomain.yaml
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Labels: AKS
