Repository Azure/azure-cli, pull requests merged in 2021-11, with the labels that each got.

#20111 {packaging} Update jsondiff to 1.3.0
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: customer-reported

#20213 {CI} Fix Azure CLI Live Test
  scripts/live_test/CLITest.yml
  scripts/live_test/generate_index.py
  scripts/live_test/sendemail.py
Labels: CI

#20264 [App Service] `az appservice` : Fix AttributeError during user error handling
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
Labels: customer-reported

#20326 [Compute] `az vm boot-diagnostics get-boot-log`: Fix boot diagnostics decoding
  src/azure-cli/azure/cli/command_modules/vm/custom.py
Labels: customer-reported

#20183 [ARM] Fix #19420: `az bicep install`: Fix the CERTIFICATE_VERIFY_FAILED for generating SSL
  src/azure-cli/azure/cli/command_modules/resource/_bicep.py
Labels: customer-reported

#20325 [App Service] Fix #11818: `az webapp ssh`, `az webapp create-remote-connection`, `az webapp log download`, `az webapp log tail`: Add proxy support
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tunnel.py
  src/azure-cli/azure/cli/command_modules/appservice/utils.py
Labels: customer-reported

#20360 [Network] `az network application-gateway waf-policy managed-rule exclusion`: Add new subgroup `rule-set` to support per rule exclusions
  src/azure-cli/azure/cli/command_modules/network/_help.py
  src/azure-cli/azure/cli/command_modules/network/_params.py
  src/azure-cli/azure/cli/command_modules/network/commands.py
  src/azure-cli/azure/cli/command_modules/network/custom.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_waf_policy_exclusion_rule_set.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network

#20305 [Network] Fix #20289: `az network bastion create` invalid validator when `--scale-units` is None
  src/azure-cli/azure/cli/command_modules/network/_validators.py
Labels: Network

#20251 [Compute] `az disk snapshot`: Add `--public-network-access` parameter to control the policy for export on the disk
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_accelerated_network.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_completion_percent.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_public_network_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute

#20355 [Network] `az network vnet`: Add `--enable-encryption` parameter to support enable encryption on virtual network
  src/azure-cli/azure/cli/command_modules/network/_params.py
  src/azure-cli/azure/cli/command_modules/network/custom.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_with_encryption.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network - Virtual Network

#20422 {RDBMS}: Handling invalid json input for pg flex server migration.
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
Labels: customer-reported

#20513 [Backup] `az backup protectable-item list/show`: Fix AttributeError for server_name
  src/azure-cli/azure/cli/command_modules/backup/custom.py
  src/azure-cli/azure/cli/command_modules/backup/custom_wl.py
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_archive.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
Labels: Backup

#20261 [App Service] `az functionapp deployment source config-zip`: Fix returning success when the deployment did not succeed
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands_thru_mock.py
Labels: customer-reported
