Repository Azure/azure-cli, pull requests merged in 2021-07, with the labels that each got.

#18636 [CosmosDB] Adding support for selecting Cosmos DB analytical storage schema type
  src/azure-cli/azure/cli/command_modules/cosmosdb/_params.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_analytical_storage_schema_type_on_create.yaml
  src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_analytical_storage_schema_type_on_update.yaml
  src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_cosmosdb_managed_service_identity.yaml
  src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/recordings/test_create_database_account.yaml
  src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
Labels: customer-reported

#18582 [App Service]: Fix an issue where adding VNET integration & Hybrid connections on a slot is not working
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_hybridconnectionE2E.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_vnetE2E.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: Web Apps

#18704 [AKS] az aks get-credentials: Add a check for KUBECONFIG environmental variable
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: customer-reported

#18721 [ARM]: Fix ARM What-If formatter
  src/azure-cli/azure/cli/command_modules/resource/_formatters.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_formatters.py
Labels: customer-reported

#18749 [Packaging] Add licenses to all Python packages
  src/azure-cli-core/LICENSE.txt
  src/azure-cli-core/MANIFEST.in
  src/azure-cli-telemetry/LICENSE.txt
  src/azure-cli-telemetry/MANIFEST.in
  src/azure-cli-testsdk/LICENSE.txt
  src/azure-cli-testsdk/MANIFEST.in
Labels: customer-reported

#18717 {IOT} Iot central track 2 migration
  src/azure-cli/azure/cli/command_modules/iot/custom.py
  src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_certificate_lifecycle.yaml
  src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_dps_lifecycle.yaml
  src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_identity_hub.yaml
  src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_iot_central_app.yaml
  src/azure-cli/azure/cli/command_modules/iot/tests/latest/recordings/test_iot_hub.yaml
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: customer-reported

#18733 [BACKUP] Added support for Customer Managed Keys(CMK) for Recovery Services Vault
  linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/backup/_client_factory.py
  src/azure-cli/azure/cli/command_modules/backup/_help.py
  src/azure-cli/azure/cli/command_modules/backup/_params.py
  src/azure-cli/azure/cli/command_modules/backup/commands.py
  src/azure-cli/azure/cli/command_modules/backup/custom.py
  src/azure-cli/azure/cli/command_modules/backup/custom_base.py
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_container.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_item.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_policy.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_protection.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_restore.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_rp.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_scenario.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_unregister_container.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_archive.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_container.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_disk_exclusion.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_encryption.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_identity.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_item.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_job.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_policy.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_protection.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_restore.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_rp.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_scenario.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_backup_softdelete.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_backup_commands.py
  src/azure-cli/recoveryconfig.json
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: customer-reported

#18793 {Redis} Migrate to Track 2 Mgmt SDK
  src/azure-cli/azure/cli/command_modules/redis/_help.py
  src/azure-cli/azure/cli/command_modules/redis/_params.py
  src/azure-cli/azure/cli/command_modules/redis/commands.py
  src/azure-cli/azure/cli/command_modules/redis/custom.py
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_export_import.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_firewall.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_list_firewall_and_server_link_works.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_list_keys.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_patch_schedule.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_reboot.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_regenerate_key_update_tags.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_server_link.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_mandatory_args.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_tags_and_zones.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/recordings/test_redis_cache_with_tlsversion_and_settings.yaml
  src/azure-cli/azure/cli/command_modules/redis/tests/latest/test_redis_scenario.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: customer-reported

#18977 {Telemetry} Import unittest.mock in telemetry test
  src/azure-cli-telemetry/azure/cli/telemetry/tests/test_telemetry_client.py
Labels: customer-reported

#19006 {ACR} Migrate to Track 2
  src/azure-cli/azure/cli/command_modules/acr/scope_map.py
  src/azure-cli/azure/cli/command_modules/acr/task.py
  src/azure-cli/azure/cli/command_modules/acr/token.py
Labels: Container Registry

#18727 [AKS] `az aks check-acr`: Fix the crashes when kubectl minor version includes non-numeric chars
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: customer-reported
