Repository Azure/azure-cli, pull requests merged in 2021-12, with the labels that each got.

#20556 {Packaging} Change default debian repo to bullseye
  scripts/release/debian/deb_install.sh
Labels: customer-reported

#20593 {vm} Update the help information of parameter `gallery_image_reference`
  src/azure-cli/azure/cli/command_modules/vm/_params.py
Labels: Compute, customer-reported

#20603 {Packaging} Fix Mariner docker file to build azure-cli rpm cleanly
  scripts/release/rpm/Dockerfile.mariner
Labels: Packaging/RPM

#20608 {Packaging} Pin `cffi` to 1.14.6 for RPM
  azure-pipelines.yml
  scripts/release/rpm/azure-cli.spec
Labels: Packaging/RPM

#20584 [Packaging] Add CI job to build Mariner RPM
  azure-pipelines.yml
  scripts/release/rpm/pipeline_mariner.sh
Labels: Packaging/RPM

#20650 {monitor} fix four testcases
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_log_profile.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_data_export.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_log_analytics_workspace_saved_search.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_analytics_workspace.py
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_log_profile.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: customer-reported

#20665 {network}add tests for two network commands
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_sku.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_public_ip_prefix.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: customer-reported

#20408 [Core] Use optimistic locking for service principal entry reads
  src/azure-cli-core/azure/cli/core/auth/persistence.py
Labels: MSAL

#20725 {Monitor} Bump `monitor` from 2.0.0 to 3.0.0
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/recordings/test_acr_create_with_audits.yaml
  src/azure-cli/azure/cli/command_modules/monitor/operations/activity_log_alerts.py
  src/azure-cli/azure/cli/command_modules/monitor/operations/subscription_diagnostic_settings.py
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_activity_log_list_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_action.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_condition.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_activity_log_alert_update_scope.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_basic.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_fixed.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_recurring.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rule_for_spring_cloud.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rule_with_dimensions.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rules.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_default_activity_log_alert.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_disabled_activity_log_alert.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_full_fledged_activity_log_alert.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_create_log_profile.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_diagnostic_settings_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_diagnostic_settings_subscription.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_metrics_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_role_assignment_audits.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_db_security_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_server_ms_support_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_server_security_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_sql_pool_audit_policy_logentry_eventhub.yaml
  src/azure-cli/azure/cli/command_modules/synapse/tests/latest/recordings/test_sql_ws_audit_policy_logentry_eventhub.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_metric_tail.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Monitor

#20726 {network} Add tests for five application-gateway commands
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_with_private_ip.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: customer-reported

#20714 {Packaging} Upgrade `virtualenv` to 16.7.11 to fix install on python 3.10
  scripts/curl_install_pypi/install
  scripts/curl_install_pypi/install.py
Labels: customer-reported

#20704 {network}add tests for six commands
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_auth_cert.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_root_cert.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_app_gateway_redirect_config.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: customer-reported

#19579 [Rest] BREAKING CHANGE: `az rest`: Remove `resourceGroup`, `x509ThumbprintHex` transforms
  src/azure-cli-core/azure/cli/core/commands/transform.py
  src/azure-cli/azure/cli/command_modules/util/custom.py
Labels: rest

#20717 {testsdk} Remove `CommunicationResourcePreparer` from `azure-cli-testsdk`
  src/azure-cli-testsdk/azure/cli/testsdk/__init__.py
  src/azure-cli-testsdk/azure/cli/testsdk/preparers.py
Labels: customer-reported

#20767 {CosmosDB} Typo "Azure CosmosDB"→"Azure Cosmos DB"
  src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py
Labels: customer-reported

#20855 {Storage} Updated the usage of az storage container restore
  src/azure-cli/azure/cli/command_modules/storage/_help.py
Labels: customer-reported
