Repository Azure/azure-cli, pull requests merged in 2022-02, with the labels that each got.

#21167 {Network} Close bastion session from cli
  src/azure-cli/azure/cli/command_modules/network/custom.py
  src/azure-cli/azure/cli/command_modules/network/tunnel.py
Labels: Network, Auto-Assign

#21171 [Network] `az bastion ssh`: Add more platforms
  src/azure-cli/azure/cli/command_modules/network/custom.py
Labels: Network, customer-reported, Auto-Assign

#21116 {CI} Verify PR title, history notes to make it more standard to reduce manual effort during release.
  .github/pull_request_template.md
  azure-pipelines.yml
  scripts/ci/check_pull_request.py
Labels: CI

#21204 {network} Fix capture limit, size and time validation issue in `az network watcher packet-capture create`.
  src/azure-cli/azure/cli/command_modules/network/_params.py
  src/azure-cli/azure/cli/command_modules/network/_validators.py
Labels: Network, Auto-Assign

#21184 {appservice} Minor spelling correction to warning message in custom.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
Labels: customer-reported

#21229 {CI} Fix index out of range error and add some comments
  scripts/ci/check_pull_request.py
Labels: CI

#21232 [Compute] `az vm create`: Fix the issue that VMCustomization is not enabled
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_size_properties.yaml
Labels: Compute, Auto-Assign

#21243 {Compute} `az vm update`: Remove space from one license type value 'SLES_STANDARD'
  src/azure-cli/azure/cli/command_modules/vm/_params.py
Labels: Compute, Auto-Assign

#21241 {Compute} Hotfix: `az vm create`: Fix the issue that VMCustomization is not enabled
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_size_properties.yaml
Labels: Compute, Auto-Assign

#21231 {RDBMS}: Switch to Offline migration by default for PG single to flex migrations
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
Labels: customer-reported

#21320 {Azure Bastion} Bug fix websocket call for insecurity
  src/azure-cli/azure/cli/command_modules/network/tunnel.py
Labels: Do Not Merge

#21300 [Compute] `az vm disk attach`: Modify help description to guide how to use the `--ids` parameter correctly
  src/azure-cli/azure/cli/command_modules/vm/_help.py
Labels: Compute

#21346 {Compute} `az vm encryption`: Fix the URL in help description
  src/azure-cli/azure/cli/command_modules/vm/_help.py
Labels: customer-reported, Auto-Assign

#21356 {CI} Verb check: Only check the first word after `]` or `:`
  scripts/ci/check_pull_request.py
Labels: CI

#21350 [Keyvault] Fix #21341: `az keyvault update`: Support updating tags
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Labels: Auto-Assign

#21371 [Keyvault] `az keyvault key create/import/set-attributes`: Support `--immutable` to mark release policy immutable
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
  src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py
  src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
  src/azure-cli/azure/cli/command_modules/keyvault/commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Auto-Assign

#21380 [Keyvault] `az keyvault key import`: Support `--kty oct` to import AES key
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
Labels: Auto-Assign

#21340 [Monitor] `az monitor log-analytics workspace table`: Add new command `restore create` and `migrate` to support Restored logs table/migrate operations
  src/azure-cli/azure/cli/command_modules/monitor/_help.py
  src/azure-cli/azure/cli/command_modules/monitor/_params.py
  src/azure-cli/azure/cli/command_modules/monitor/commands.py
  src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Auto-Assign

#21354 [Compute] `az vmss create/update`: Add new parameters `--security-type`, `--enable-secure-boot` and `--enable-vtpm` to support Trusted Launch
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_trusted.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Auto-Assign

#21284 [Network] `az network private-endpoint`: Associate IP configurations and ASGs when creating PE
  src/azure-cli/azure/cli/command_modules/network/_actions.py
  src/azure-cli/azure/cli/command_modules/network/_help.py
  src/azure-cli/azure/cli/command_modules/network/_params.py
  src/azure-cli/azure/cli/command_modules/network/custom.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_asg.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoint_ip_config.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_private_endpoints.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#21383 [AKS] `az aks get-credentials`: Add new parameter `--format` to support specify the format of returned credential
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/_validators.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
Labels: Auto-Assign

#21408 {CI} Fix live test password is expired error.
  scripts/live_test/CLITest.yml
Labels: CI, Auto-Assign

#21379 {AKS} az aks nodepool list fix for #19681
  src/azure-cli/azure/cli/command_modules/acs/_help.py
Labels: Auto-Assign

#20485 [Compute] `az vmss create/update`: Add new parameters `--automatic-repairs-action` to support repair action
  linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/_validators.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_create_automatic_repairs_with_health_probe.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_automatic_repairs_with_health_probe.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#21381 {ACS} Addition to --context description fixes #19779
  src/azure-cli/azure/cli/command_modules/acs/_params.py
Labels: AKS

#21370 {Compute} `az vmss run-command invoke`: Fix help message
  src/azure-cli/azure/cli/command_modules/vm/_help.py
Labels: Auto-Assign

#21368 [Compute] `az vmss create/update`: Add new parameters `--v-cpus-available` and `--v-cpus-per-core` to support VMSize customization
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_size_properties.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Auto-Assign

#21419 {AppConfig} Fix #13498958: Fix errors with az appconfig revision list when using customized fields
  scripts/ci/credscan/CredScanSuppressions.json
  src/azure-cli/azure/cli/command_modules/appconfig/keyvalue.py
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_appconfig_to_appconfig_import_export.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_aad_auth.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_credential.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_feature.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_feature_filter.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_feature_namespacing.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_identity.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_import_export.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_import_export_kvset.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_import_export_naming_conventions.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_json_content_type.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_key_validation.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_kv.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_kv_revision_list.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_local_auth.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_public_network_access.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_azconfig_strict_import.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/recordings/test_resolve_keyvault.yaml
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
Labels: App Configuration
