Repository Azure/azure-cli, pull requests merged in 2022-01, with the labels that each got.

#20716 [Bot Service] `az bot create`: Add location as specified by user to bot creation for regionality/EUDB
  src/azure-cli/azure/cli/command_modules/botservice/custom.py
Labels: customer-reported

#21048 {packaging} Update Fedora dockerfile to Fedora 35
  scripts/release/rpm/Dockerfile.fedora
Labels: customer-reported

#21079 [Packaging] Update Dockerfile base image from Alpine 3.14 to 3.15
  Dockerfile
Labels: customer-reported

#20567 {RDBMS} Fix PHP wrong connection strings
  src/azure-cli/azure/cli/command_modules/rdbms/custom.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py
Labels: customer-reported

#21096 [Network] Add Microsoft.HybridCompute/privateLinkScopes to supported Private Endpoints
  src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Labels: Network, Auto-Assign

#21109 {Network} `az network application-gateway update` update example
  src/azure-cli/azure/cli/command_modules/network/_help.py
Labels: Network, customer-reported, Auto-Assign

#20051 {Role} Change "directory administrator" to "global administrator"
  src/azure-cli/azure/cli/command_modules/role/_help.py
Labels: customer-reported

#21077 {iot} Fix: typo in az iot hub route update docs
  src/azure-cli/azure/cli/command_modules/iot/_help.py
Labels: customer-reported

#21123 {Iot} Use correct params in iot hub route examples
  src/azure-cli/azure/cli/command_modules/iot/_help.py
Labels: customer-reported
