Repository Azure/azure-cli, pull requests merged in 2023-10, with the labels that each got.

#26923 [Packaging] Support Python 3.11
  azure-pipelines-full-tests.yml
  azure-pipelines.yml
  scripts/ci/build.sh
  src/azure-cli-core/azure/cli/core/telemetry.py
  src/azure-cli-core/azure/cli/core/tests/test_command_registration.py
  src/azure-cli-core/azure/cli/core/tests/test_help.py
  src/azure-cli-core/azure/cli/core/tests/test_parser.py
  src/azure-cli-core/azure/cli/core/util.py
  src/azure-cli-core/setup.py
  src/azure-cli-telemetry/setup.py
  src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/utilities.py
  src/azure-cli-testsdk/setup.py
  src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_custom_domain_scenarios.py
  src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_afd_route_scenarios.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_t1/key_vault_authentication.py
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
  src/azure-cli/setup.py
Labels: Packaging, Auto-Assign

#26749 [Packaging] Bump embedded Python version to 3.11.5
  Dockerfile
  build_scripts/windows/scripts/build.cmd
  scripts/release/debian/build.sh
  scripts/release/homebrew/docker/formula_generate.py
Labels: Packaging, Auto-Assign

#27534 [containerapp] `az containerapp job create`: Fix AttributeError when `--trigger-type` is None
  src/azure-cli/azure/cli/command_modules/containerapp/containerapp_env_decorator.py
  src/azure-cli/azure/cli/command_modules/containerapp/containerapp_job_decorator.py
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_container_app_mount_azurefile_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_certificate_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_custom_domains.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_dapr_components.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_internal_only_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_logs_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_mtls.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_env_update_custom_domains.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_eventjob_crudoperations_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_identity_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_job_custom_executionstest_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_job_executionstest_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_manualjob_crudoperations_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_manualjob_private_registry_port.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_manualjob_registry_acr_look_up_credentical.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_manualjob_withidentity_crudoperations_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_manualjob_withsecret_crudoperations_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_create_with_environment_id.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_create_with_yaml.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_eventtriggered_create_with_yaml.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_env_commands.py
Labels: Auto-Assign, ContainerApp

#27493 [Compute] Fix #27446: `az vm encryption enable`: Fix using incorrect client when `--key-encryption-key` is specified
  src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/disk_encryption.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_encryption_with_key.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#27416 [EventHub/ServiceBus] BREAKING CHANGE: `az servicebus migration update` `az servicebus georecovery-alias update` `az evernthubs georecovery-alias update` Remove Deprecated cmdlets
  src/azure-cli/azure/cli/command_modules/eventhubs/_params.py
  src/azure-cli/azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/georecovery_alias/__init__.py
  src/azure-cli/azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/georecovery_alias/_update.py
  src/azure-cli/azure/cli/command_modules/eventhubs/commands.py
  src/azure-cli/azure/cli/command_modules/servicebus/_params.py
  src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/georecovery_alias/__init__.py
  src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/georecovery_alias/_update.py
  src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/migration/__init__.py
  src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/migration/_update.py
  src/azure-cli/azure/cli/command_modules/servicebus/commands.py
Labels: Service Bus, Auto-Assign

#27483 {Mysql} az mysql flexible-server: Update cli for breaking changes in latest sdk
  src/azure-cli/azure/cli/command_modules/mysql/_util.py
  src/azure-cli/azure/cli/command_modules/mysql/custom.py
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_export.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_backups_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_byok_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_check_name_availability_fallback_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_cross_region_replica_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_existing_private_dns_zone.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_georestore_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_georestore_update_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_gtid_reset.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_identity_aad_admin_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_import_create.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_iops_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_mgmt_create_validator.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_mgmt_update_validator.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_new_private_dns_zone.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_paid_iops_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_proxy_resource.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_public_access_custom.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_public_access_georestore.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_public_access_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_public_access_restore.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_replica_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_restore_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_upgrade_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_subnet_id_in_different_rg.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_subnetid.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_vnet_mgmt_supplied_vname_and_subnetname.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/test_mysql_scenario.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_mariadb_private_link_scenario.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_mysql_flexible_server.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_mysql_flexible_server.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_proxy_resources_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mariadb_server_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_mysql_server_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_server_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_commands.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Auto-Assign

#27458 [Network] `az network private-dns record-set a add-record`: Fix record cannot be added when record set is empty
  src/azure-cli/azure/cli/command_modules/privatedns/custom.py
  src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/recordings/test_add_record_when_record_set_is_empty.yaml
  src/azure-cli/azure/cli/command_modules/privatedns/tests/latest/test_privatedns_commands.py
Labels: Network, Auto-Assign

#27541 {Packaging} Fix DEB package build and test
  scripts/release/debian/prepare.sh
  scripts/release/debian/test_deb_package.py
Labels: Packaging, Auto-Assign

#27546 {Mysql} az mysql flexible-server import create: Adding logic for external migration
  src/azure-cli/azure/cli/command_modules/mysql/_help.py
  src/azure-cli/azure/cli/command_modules/mysql/_params.py
  src/azure-cli/azure/cli/command_modules/mysql/_validators.py
  src/azure-cli/azure/cli/command_modules/mysql/custom.py
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_import_create.yaml
Labels: Auto-Assign

#27544 {Core} Remove restrictions for parameters `zones_type` and `zone_type` to support more than 3 zones
  src/azure-cli-core/azure/cli/core/commands/parameters.py
  src/azure-cli/azure/cli/command_modules/network/_params.py
Labels: Core, Auto-Assign

#27478 {Packaging} Bump antlr4-python3-runtime to 4.13.1
  src/azure-cli/azure/cli/command_modules/monitor/grammar/autoscale/AutoscaleConditionLexer.py
  src/azure-cli/azure/cli/command_modules/monitor/grammar/autoscale/AutoscaleConditionListener.py
  src/azure-cli/azure/cli/command_modules/monitor/grammar/autoscale/AutoscaleConditionParser.py
  src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionLexer.py
  src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionListener.py
  src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionParser.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Monitor, Auto-Assign

#27572 [Compute] Fix #27451: `az vmss list-instances`: Fix API profile to resolve no registered resource provider found error
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vmss_create_and_modify.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vmss_create_options.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vmss_vms.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_create_and_modify.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_create_options.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_nics.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_update_instance_disks.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vmss_vms.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_create_and_modify.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_create_options.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_nics.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_simulate_eviction.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_update_instance_disks.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vmss_vms.yaml
Labels: Compute, Auto-Assign

#27569 {Backup} `az backup protection check-vm`: Update help message
  src/azure-cli/azure/cli/command_modules/backup/_help.py
Labels: Backup, Auto-Assign

#27574 [Network] `az network application-gateway listener`: Add parameter `--host-names`
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_create.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_delete.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_list.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_show.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_update.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/application_gateway/listener/_wait.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_ag_rule_default_exists.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_appgw_with_tcp.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_listener.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_listener_with_host_names.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_ag_routing_rule.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#27591 {Mysql} az mysql flexible-server import create: Change sku to default for external migration
  src/azure-cli/azure/cli/command_modules/mysql/_help.py
  src/azure-cli/azure/cli/command_modules/mysql/_params.py
  src/azure-cli/azure/cli/command_modules/mysql/custom.py
Labels: Auto-Assign

#27592 {AKS} Fix #27461: `az aks create`: Update help information for option `--node-osdisk-size`
  src/azure-cli/azure/cli/command_modules/acs/_help.py
Labels: AKS, Auto-Assign

#27597 [monitor]`az monitor autoscale update`: Fix update failure with empty notification
  src/azure-cli/azure/cli/command_modules/monitor/operations/autoscale_settings.py
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_basic.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_fixed.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_predictive_policy.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_recurring.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_refined.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rule_with_dimensions.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_rules.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_autoscale_show_predictive_metric.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py
Labels: Monitor, Auto-Assign

#27204 [Packaging] Add Azure Linux docker image
  .dockerignore
  alpine.dockerfile
  azure-linux.dockerfile
  azure-pipelines.yml
  scripts/release/docker/pipeline.sh
Labels: Packaging, Auto-Assign

#27554 AKS] `az aks update`: Fix bug where supportPlan can be reset to None
  src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#27553 [SQL] `az sql db create/update`: Add `--use-free-limit` and `--free-limit-exhaustion-behavior` arguments
  src/azure-cli/azure/cli/command_modules/sql/_help.py
  src/azure-cli/azure/cli/command_modules/sql/_params.py
  src/azure-cli/azure/cli/command_modules/sql/custom.py
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_db_free_params.yaml
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
Labels: SQL, Auto-Assign

#27619 [Keyvault] BREAKING CHANGE: `az keyvault storage`: Remove this command group since service doesn't maintain anymore
  src/azure-cli/azure/cli/command_modules/keyvault/_help.py
  src/azure-cli/azure/cli/command_modules/keyvault/_params.py
  src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
  src/azure-cli/azure/cli/command_modules/keyvault/commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
  src/azure-cli/azure/cli/command_modules/keyvault/tests/hybrid_2020_09_01/test_keyvault_commands.py
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_storage_account.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Labels: Storage, KeyVault, Auto-Assign

#27585 [containerapp] `az containerapp compose create`: Fix bug where environment's resource group is not resolved from `--environment` when the input value is a resource id
  src/azure-cli/azure/cli/command_modules/containerapp/custom.py
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_basic_no_existing_resources.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_basic.py
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/utils.py
Labels: Auto-Assign, ContainerApp

#27378 [ARM] `az bicep lint`: Add new command to lint a bicep file
  src/azure-cli/azure/cli/command_modules/resource/_help.py
  src/azure-cli/azure/cli/command_modules/resource/_params.py
  src/azure-cli/azure/cli/command_modules/resource/commands.py
  src/azure-cli/azure/cli/command_modules/resource/custom.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_custom.py
Labels: ARM, Auto-Assign

#26464 [Packaging] Fix #22741: `az upgrade`: This command becomes non-blocking on Windows
  src/azure-cli/azure/cli/command_modules/util/custom.py
Labels: Packaging, Auto-Assign

#27622 [Storage] `az storage file/directory`: Trailing dot support GA, default action changes from trimming trailing dot in file/directory names to not trimming, add `--disallow-trailing-dot` and `--disallow-source-trailing-dot`
  src/azure-cli/azure/cli/command_modules/storage/_client_factory.py
  src/azure-cli/azure/cli/command_modules/storage/_params.py
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_trailing_dot_scenario.yaml
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_scenarios.py
Labels: Storage, Auto-Assign

#27593 [Storage] Fix #27590: `az storage fs directory download`: Check user sytem PATH for azcopy and use CLI config directory for new install
  src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
Labels: Storage, Auto-Assign

#27610 {Service Connector} `az containerapp connection`: Load the command group even if container app extension is not installed
  src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
Labels: Auto-Assign, Service Connector

#27627 [Network] `az network private-endpoint-connection`: Add provider `Microsoft.DocumentDB/mongoClusters`
  src/azure-cli/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_endpoint_connection_cosmosdb_mongo_clusters.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_private_link_resource_cosmosdb_mongo_clusters.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py
Labels: Network, CosmosDB, Auto-Assign

#27621 [AKS] `az aks nodepool add`: Fix incorrectly specified property name for option `--drain-timeout`
  src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
Labels: AKS, Auto-Assign

#27647 {CI} Backport fixes to `release` branch
  src/azure-cli-core/azure/cli/core/auth/binary_cache.py
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/test_vm_image.py
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/test_vm_image.py
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_vm_image.py
Labels: CI, Auto-Assign

#27565 [App Service] BREAKING CHANGE: Redact appsettings output on set/delete
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/static_sites.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_version_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_swap.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_logicapp_config_appsettings_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_staticapp_appsettings.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_update_webapp_settings_thru_json.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config_appsettings.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_logicapp_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_staticapp_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: Web Apps, Functions, Logic App, customer-reported, Auto-Assign

#27618 [Network] Modify the example in command `az network lb create`
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_create.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_list.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/lb/_list_nic.py
Labels: Network, Auto-Assign

#27558 {Servicebus} `az servicebus queue` documentation update
  src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/queue/_create.py
  src/azure-cli/azure/cli/command_modules/servicebus/aaz/latest/servicebus/queue/_update.py
Labels: Service Bus, Auto-Assign

#27559 [Network] Fix #27508: `az network private-dns zone import`: Import fails when zone already exists
  src/azure-cli/azure/cli/command_modules/privatedns/custom.py
Labels: Network, Auto-Assign

#27664 [AKS] `az aks update`: Fix bug where supportPlan can be reset to None
  src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#27648 {monitor}`az monitor clone`: Migrate command to codegen V2
  src/azure-cli/azure/cli/command_modules/monitor/operations/monitor_clone_util.py
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_public_ip_metric_alerts_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_storage_metric_alerts_always_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_storage_metric_alerts_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/recordings/test_monitor_clone_vm_metric_alerts_scenario.yaml
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_general_operations.py
Labels: Monitor, Auto-Assign

#27640 {Mysql} az mysql flexible-server import create: Add firewall rule migration from single to flex
  src/azure-cli/azure/cli/command_modules/mysql/_client_factory.py
  src/azure-cli/azure/cli/command_modules/mysql/_params.py
  src/azure-cli/azure/cli/command_modules/mysql/_util.py
  src/azure-cli/azure/cli/command_modules/mysql/_validators.py
  src/azure-cli/azure/cli/command_modules/mysql/custom.py
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_import_create.yaml
Labels: Auto-Assign

#27567 [Packaging] BREAKING CHANGE: Remove unnecessary packages in docker image
  alpine.dockerfile
Labels: Packaging, Auto-Assign

#27527 [ARM] `az deployment group create`: Support supplemental parameters when used with `.bicepparam` parameter file
  src/azure-cli/azure/cli/command_modules/resource/_bicep.py
  src/azure-cli/azure/cli/command_modules/resource/custom.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/sample_params.bicep
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/sample_params.bicepparam
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Labels: ARM, Auto-Assign

#27665 {Service Connector} Add new client type: `dotnet-internal`
  src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
Labels: Service Connector

#27717 {CI} Disable `alias` extension test
  scripts/ci/test_extensions.sh
Labels: Packaging, Auto-Assign
