Repository Azure/azure-cli, pull requests merged in 2024-12, with the labels that each got.

#30339 {Core} Add dict transformation for typespec generated SDKs
  src/azure-cli-core/azure/cli/core/commands/__init__.py
  src/azure-cli-core/azure/cli/core/util.py
  src/azure-cli/azure/cli/command_modules/keyvault/_transformers.py
  src/azure-cli/azure/cli/command_modules/keyvault/commands.py
Labels: Core, Auto-Assign

#30434 {CI} Fix file name space when iterating git diffs for secret scan task
  .githooks/pre-commit.sh
  azure-pipelines.yml
Labels: CI, Auto-Assign

#30448 {Misc} Don't use aliased io.open
  src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
  src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py
  src/azure-cli/azure/cli/command_modules/containerapp/_archive_utils.py
Labels: customer-reported

#30449 {Misc} Remove __future__ Python 2.7 imports
  src/azure-cli-core/azure/cli/core/commands/progress.py
  src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py
  src/azure-cli/azure/cli/command_modules/acs/_validators.py
Labels: customer-reported

#30452 {Misc} Fix UP022. Use capture_output for subprocess.run.
  src/azure-cli/azure/cli/command_modules/resource/_bicep.py
  src/azure-cli/azure/cli/command_modules/security/_utils.py
Labels: customer-reported

#30451 {Misc} Remove various Python 2.7 ImportError
  scripts/curl_install_pypi/install.py
  src/azure-cli-core/azure/cli/core/aaz/_operation.py
  src/azure-cli-core/azure/cli/core/keys.py
  src/azure-cli-telemetry/azure/cli/telemetry/__init__.py
  src/azure-cli-telemetry/azure/cli/telemetry/components/telemetry_client.py
  src/azure-cli-telemetry/azure/cli/telemetry/tests/test_telemetry_client.py
  src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
  src/azure-cli/azure/cli/command_modules/acr/manifest.py
  src/azure-cli/azure/cli/command_modules/acr/repository.py
  src/azure-cli/azure/cli/command_modules/acr/tests/hybrid_2020_09_01/test_acr_commands_mock.py
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
  src/azure-cli/azure/cli/command_modules/botservice/kudu_client.py
  src/azure-cli/azure/cli/command_modules/botservice/web_app_operations.py
  src/azure-cli/azure/cli/command_modules/iot/sas_token_auth.py
  src/azure-cli/azure/cli/command_modules/lab/validators.py
  src/azure-cli/azure/cli/command_modules/resource/_validators.py
  src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
  src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
  src/azure-cli/azure/cli/command_modules/vm/_image_builder.py
  src/azure-cli/azure/cli/command_modules/vm/_validators.py
  src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_image_builder.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_validators.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_vm_utils.py
  tools/automation/utilities/pypi.py
Labels: customer-reported

#30464 {Core} Stop using legacy `base64.decodebytes`
  src/azure-cli-core/azure/cli/core/keys.py
  src/azure-cli/azure/cli/command_modules/lab/validators.py
Labels: Compute, Auto-Assign

#30473 {Misc} Remove Python 3.8 typing fallbacks
  src/azure-cli/azure/cli/command_modules/containerapp/_sdk_models.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/_internal/async_challenge_auth_policy.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/_model_base.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/_operations/_operations.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/aio/_operations/_operations.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/aio/_patch.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/aio/operations/_operations.py
  src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_securitydomain/operations/_operations.py
Labels: customer-reported

#30492 {CDN} skip 2 cdn migration unit tests which are breaking pipeline
  src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_classic_cdn_migration_abort.yaml
  src/azure-cli/azure/cli/command_modules/cdn/tests/latest/recordings/test_classic_cdn_migration_with_endpoint.yaml
  src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_classic_cdn_to_afd.py
Labels: Network, Network - CDN, Auto-Assign

#30474 {Misc} Remove misc Python 2.7 fallbacks.
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py
  src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_streaming_endpoint_scenarios.py
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
  src/azure-cli/azure/cli/command_modules/botservice/bot_json_formatter.py
  src/azure-cli/azure/cli/command_modules/botservice/bot_publish_prep.py
  src/azure-cli/azure/cli/command_modules/monitor/grammar/autoscale/AutoscaleConditionParser.py
  src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertConditionParser.py
  src/azure-cli/azure/cli/command_modules/resource/custom.py
Labels: customer-reported

#30426 {Misc} Fix F601 errors. Duplicate dictionary keys.
  src/azure-cli/azure/cli/command_modules/appconfig/tests/latest/test_appconfig_commands.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: customer-reported

#30500 [SQL] `az sql db ltr-policy`: Remove preview tag
  src/azure-cli/azure/cli/command_modules/sql/commands.py
Labels: SQL, customer-reported, Auto-Assign

#30421 [RDBMS] `az postgres flexible-server fabric-mirroring/identity`: Support system assigned managed identity and fabric mirroring of databases
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_fabric_mirroring_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
Labels: Auto-Assign

#30508 {CI} Enable component detection in release branch
  azure-pipelines.yml
Labels: CI, Auto-Assign

#30513 {CI} Optimize azure-cli githook
  .githooks/pre-push.ps1
  .githooks/pre-push.sh
Labels: CI, Auto-Assign

#30510 [Storage] Fix #28554: `az storage blob service-properties update`: Support cases where `--static-website false` and index and 404 documents were already set
  src/azure-cli/azure/cli/command_modules/storage/operations/blob.py
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_blob_update_service_properties.yaml
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_blob_scenarios.py
Labels: Storage, Portal, Auto-Assign

#30485 [ACR] `az acr agentpool`: Fix delete polling
  src/azure-cli/azure/cli/command_modules/acr/agentpool.py
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_agentpool_commands.py
Labels: Container Registry, Auto-Assign

#30404 [ACR] `az acr create`: Add validation for registry name to support domain name label
  src/azure-cli/azure/cli/command_modules/acr/_constants.py
  src/azure-cli/azure/cli/command_modules/acr/_validators.py
  src/azure-cli/azure/cli/command_modules/acr/custom.py
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands.py
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_validators.py
Labels: Container Registry, Auto-Assign

#30533 {Packaging} Bump embedded Python version to 3.12.8
  build_scripts/windows/scripts/build.cmd
  scripts/release/debian/build.sh
Labels: Packaging, Auto-Assign

#30521 [Keyvault] `az keyvault key sign/verify`: Fix `--digest` to accept base64 encoded string
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/recordings/test_keyvault_key.yaml
  src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py
Labels: KeyVault, Auto-Assign

#30534 {Storage} Fix #30377: `az storage entity insert`: Add instructions for specifying odata type
  src/azure-cli/azure/cli/command_modules/storage/_help.py
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_table_main_scenario.yaml
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_table_scenarios.py
Labels: Storage, Auto-Assign

#30539 {AKS} `az aks create/update`: Outbound type should not be updated if it is not set
  src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#30561 {AKS} `az aks install-cli`: Add error message wrapper
  src/azure-cli/azure/cli/command_modules/acs/custom.py
Labels: AKS, Installation, Auto-Assign

#30572 [RDBMS] `az postgres flexible-server update`: Add `--node-count` argument to scale up elastic clusters
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_citus_on_flex_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
Labels: Auto-Assign

#30540 [LTS] Backport #30092
  src/azure-cli-core/azure/cli/core/auth/identity.py
  src/azure-cli-core/azure/cli/core/auth/tests/test_identity.py
  src/azure-cli-core/azure/cli/core/auth/util.py
  src/azure-cli/azure/cli/command_modules/profile/_help.py
  src/azure-cli/azure/cli/command_modules/profile/custom.py
Labels: Account, Auto-Assign

#30549 {RDBMS} `az postgres flexible-server create`: Sort version number, sku name when displaying the error message
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#30537 {RDBMS} Add warnings that selecting PG version 12 will no longer be supported in `az postgres flexible-server upgrade`
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
Labels: Auto-Assign

#30552 {RDBMS} `az postgres server, az postgres db, az postgres server-logs `: Add warnings that Azure Database for PostgreSQL - Single Server is on the retirement path
  src/azure-cli/azure/cli/command_modules/rdbms/_help.py
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/custom.py
Labels: Auto-Assign

#30569 [Storage] Fix #29929: `az storage copy`: Fix when wildcard `*` is in `--source-file-path`
  src/azure-cli/azure/cli/command_modules/storage/_validators.py
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_azcopy_scenarios.py
Labels: Storage, Auto-Assign

#30578 {cdn}skip cdn migration commit ut
  src/azure-cli/azure/cli/command_modules/cdn/tests/latest/test_classic_cdn_to_afd.py
Labels: Network, Network - CDN, Auto-Assign

#30568 [Compute] `az vm create`: Fix creating VM with `--patch-mode` or `--enable-auto-update` parameters
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_linux_vm_patch_mode.yaml
Labels: Compute, Auto-Assign
