Repository Azure/azure-cli, pull requests merged in 2024-09, with the labels that each got.

#29769 [Packaging] Release Docker image based on Azure Linux 3.0
  azure-linux.dockerfile
  azure-pipelines.yml
  scripts/release/docker/pipeline.sh
Labels: Packaging, Auto-Assign

#29859 {CI} Update TriggerReferenceDocsCI.yml
  .github/workflows/TriggerReferenceDocsCI.yml
Labels: CI, Auto-Assign

#29840 {RDBMS} `az postgres flexible-server update`: Support Case-Insensitive Input for `--tier`, `--performance-tier`, `--sku`, and `--maintenance-window`
  src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_flexible_server_ssdv2_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_flexible_server_ssdv2_restore_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_mgmt_case_insensitive.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_mgmt_update_validator.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Backup, Auto-Assign

#29864 {RDBMS} `az postgres flexible-server migration create`: Fix passing in json properties for source and target domain names
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
Labels: Auto-Assign

#29867 [Packaging] Include `jq` in Azure Linux docker image
  azure-linux.dockerfile
Labels: Packaging, Auto-Assign

#29869 {afd} `az afd origin create`,`az afd endpoint purge` parameters documents update
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin/_create.py
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin/_update.py
Labels: Network - Front Door, Auto-Assign

#29741 {Packaging} Drop Alpine docker image
  alpine.dockerfile
  azure-pipelines.yml
  scripts/release/rpm/centos7.dockerfile
Labels: Packaging, Auto-Assign

#29863 [RDBMS] `az postgres flexible-server migration create` Add AWS_AURORA as a migration source type for PostgreSql
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
Labels: Auto-Assign

#29886 [SQL] `az sql elastic-pool create`: Set `min_capacity` to `None` for non-serverless SKUs
  src/azure-cli/azure/cli/command_modules/sql/custom.py
Labels: SQL, Auto-Assign

#29858 {AKS} Remove dependency on `azure.graphrbac`
  src/azure-cli/azure/cli/command_modules/acs/_graph.py
Labels: AKS, Auto-Assign

#29879 [dla] `az dla`: Deprecate azure datalake analytics from CLI
  src/azure-cli/azure/cli/command_modules/dla/commands.py
Labels: Synapse, Auto-Assign

#27196 {Packaging} Add `setuptools` into dependency
  src/azure-cli/setup.py
Labels: Packaging, Installation, Auto-Assign

#29813 [NetAppFiles] `az netappfiles volume create`: Fix subnet id as resource id
  src/azure-cli/azure/cli/command_modules/netappfiles/custom.py
  src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_create_volume_with_subnet_in_different_rg.yaml
  src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_volume_size_50Gib.yaml
  src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/recordings/test_volume_size_8Tib.yaml
  src/azure-cli/azure/cli/command_modules/netappfiles/tests/latest/test_volume_commands.py
  src/azure-cli/azure/cli/command_modules/netappfiles/validators.py
Labels: NetAppFiles, Auto-Assign

#29706 {Core} Remove uuid workaround code
  src/azure-cli/azure/cli/__main__.py
Labels: Core, Auto-Assign

#29378 [Packaging] Drop Debian 10 support
  azure-pipelines.yml
Labels: Packaging, Auto-Assign

#29488 {Role} Fix typo for `az role assignment create --help`
  src/azure-cli/azure/cli/command_modules/role/_params.py
Labels: RBAC, customer-reported, Auto-Assign

#29874 {Cosmos DB} `az cosmosdb postgres` Fix invalid escapes
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/cluster/server/_show.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/_show.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/coordinator/_show.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/coordinator/_update.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/coordinator/_wait.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/node/_show.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/node/_update.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/node/_wait.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/configuration/server/_list.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_create.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_delete.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_show.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_update.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/firewall_rule/_wait.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_create.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_delete.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_show.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_update.py
  src/azure-cli/azure/cli/command_modules/cosmosdb/aaz/latest/cosmosdb/postgres/role/_wait.py
Labels: CosmosDB, Auto-Assign

#27443 [Profile] `az login`: Fall back to device code flow in GitHub Codespaces
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/tests/test_profile.py
  src/azure-cli-core/azure/cli/core/util.py
Labels: Account, Core, Auto-Assign

#29907 [containerapp] Fix #29849: `az containerapp job stop`: Fix stop execution response
  src/azure-cli/azure/cli/command_modules/containerapp/_clients.py
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_job_custom_executionstest_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_job_executionstest_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_stop_job_deprecate_arguments.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_create_with_yaml.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_eventtriggered_create_with_yaml.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_executions.py
Labels: Auto-Assign, ContainerApp

#29884 {RDBMS} `az postgres flexible-server replica create`: Update replica create help text to show example of cross resource group creation
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
Labels: Auto-Assign

#29817 [Network] `az network vnet peering`: Refine command interface of subnet peering
  linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/peering/_create.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet/peering/_update.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering_with_params.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#29924 {Keyvault} Fix typo
  src/azure-cli/azure/cli/command_modules/keyvault/_validators.py
Labels: customer-reported

#29901 {ACR} fix az acr build context match rules
  src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py
  src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_archive_utils.py
Labels: Container Registry, Auto-Assign

#29933 [Containerapp] Fix #29166: `az containerapp compose create`: Support image with tag and support get ACR from image
  src/azure-cli/azure/cli/command_modules/containerapp/_compose_utils.py
  src/azure-cli/azure/cli/command_modules/containerapp/_up_utils.py
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_and_password.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_from_image.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_without_image_tag_and_use_existing_registry_server_and_password.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerapp_compose_registries.py
Labels: Auto-Assign, ContainerApp

#29880 {Core} Register Upcoming Breaking Change on Empty Command Group
  src/azure-cli-core/azure/cli/core/breaking_change.py
Labels: Core, Auto-Assign

#29756 [AppService] Fix #29733: `az functionapp config set`: Map parameters explicitly for the internal update_site_configs function call
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_config_set.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Labels: Functions, Auto-Assign

#29952 {CI} Disable too-many-positional-arguments R0917
  pylintrc
Labels: CI, Auto-Assign

#29951 {Containerapp} Remove secrets from recording files
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_and_password.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_with_image_tag_and_use_existing_registry_server_from_image.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_compose_create_without_image_tag_and_use_existing_registry_server_and_password.yaml
Labels: Auto-Assign, ContainerApp

#29926 [Compute] `az vm/vmss create`: Add `--ssh-key-type` parameter to support generating Ed25519 SSH keys
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_validators.py
  src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_ssh_key_ed25519.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#28590 {Core} Credential handler with 1es sdk
  src/azure-cli-core/azure/cli/core/commands/__init__.py
  src/azure-cli-core/azure/cli/core/credential_helper.py
  src/azure-cli-core/azure/cli/core/telemetry.py
  src/azure-cli-core/azure/cli/core/tests/test_credential_helper.py
  src/azure-cli-core/setup.py
Labels: Core, Auto-Assign

#29810 [ACR] `az acr credential-set`: Improve help message
  src/azure-cli/azure/cli/command_modules/acr/_help.py
Labels: Container Registry, Auto-Assign

#29921 [AKS] `az aks nodepool delete-machines`: Add support to delete specific machines in an agent pool
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/commands.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#29979 {CI} Enable security issue scanning for azure-cli repo
  .github/workflows/RunIssueSentinel.yml
Labels: CI, Auto-Assign
