Repository Azure/azure-cli, pull requests merged in 2025-01, with the labels that each got.

#30548 {RDBMS} `az postgres flexible-server create`: Support Case-Insensitive Input for `--public-access`
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#30583 {RDBMS} `az postgres flexible-server private-endpoint-connection / private-link-resource / server-logs / virtual-endpoint list`: Add linter exclusion to fix linting
  src/azure-cli/azure/cli/command_modules/rdbms/linter_exclusions.yml
Labels: Auto-Assign

#30582 {RDBMS} `az postgres flexible-server create`: Fix the comparator for sorting sku name so it also sort the core number too when displaying the error message
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Core, Auto-Assign

#30588 {RDBMS} `az postgres flexible-server identity_remove`: Add a check to determine whether the user identity is used for geo backup data encryption
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
Labels: Auto-Assign

#30230 [Microsoft Entra ID] `az ad app create/update`: Add `--requested-access-token-version` argument
  src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_objects.py
  src/azure-cli/azure/cli/command_modules/role/_params.py
  src/azure-cli/azure/cli/command_modules/role/custom.py
  src/azure-cli/azure/cli/command_modules/role/linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_app_create_idempotent.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_app_scenario.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py
Labels: Graph, Auto-Assign

#30470 [Role] BREAKING CHANGE: `az role assignment delete`: Stop deleting all role assignments by default
  src/azure-cli/azure/cli/command_modules/role/_help.py
  src/azure-cli/azure/cli/command_modules/role/_params.py
  src/azure-cli/azure/cli/command_modules/role/custom.py
  src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role_commands_thru_mock.py
Labels: RBAC, Auto-Assign

#30602 {CI} Install specific version in script
  scripts/release/debian/verify_debian_in_docker.sh
  scripts/release/rpm/verify_rpm_in_docker.sh
Labels: Installation, CI, Auto-Assign

#30596 {Compute} `az vm create/update`: Add new parameter --enable-user-reboot-scheduled-events to support setting scheduled event policy
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_scheduled_events_policy.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#30397 [Container] `az container exec`: Fix exception when stdin is not a tty
  src/azure-cli/azure/cli/command_modules/container/custom.py
Labels: Auto-Assign

#30611 {doc} Fix disallowed html tags
  src/azure-cli/azure/cli/command_modules/appservice/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/storage/_help.py
Labels: Batch, Auto-Assign

#30592 [Network] Fix #30535: `az network lb address-pool address add`: Address level may not have virtual network property
  src/azure-cli/azure/cli/command_modules/network/operations/load_balancer.py
Labels: Network, Auto-Assign

#30532 {Packaging} Bump argcomplete to 3.5.2
  src/azure-cli-core/azure/cli/core/tests/test_argcomplete.py
  src/azure-cli-core/setup.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
Labels: Compute, Packaging, ARM, Auto-Assign

#30623 [Core] `aaz`: Support simple type parsed from string value
  src/azure-cli-core/azure/cli/core/aaz/_field_type.py
  src/azure-cli-core/azure/cli/core/tests/test_aaz_field.py
Labels: Core, Auto-Assign

#30155 {CI} how_to_introduce_breaking_changes.md | add more info on required properties
  doc/how_to_introduce_breaking_changes.md
Labels: CI, Auto-Assign

#30640 {Storage} Fix #30635: `az storage copy`: Use Azure FrontDoor instead of Edgio endpoint for the installation link which has been deprecated
  src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py
Labels: Storage, Auto-Assign

#30587 {Role} `az role definition list`: Use `roleName` filter when `--name` is a non-GUID string
  src/azure-cli/azure/cli/command_modules/role/_params.py
  src/azure-cli/azure/cli/command_modules/role/custom.py
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_built_in_role_definition_scenario.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_custom_role_definition_scenario.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_role_definition_scenario.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
  src/azure-cli/azure/cli/command_modules/role/tests/util.py
Labels: RBAC, Auto-Assign

#30630 [ServiceConnector] `az webapp connection create redis`: Add `--system-identity` param
  src/azure-cli/azure/cli/command_modules/serviceconnector/_resource_config.py
  src/azure-cli/azure/cli/command_modules/serviceconnector/_validators.py
Labels: Auto-Assign

#30606 {Compute} `az sig share`: Migrate command group to aaz based
  src/azure-cli/azure/cli/command_modules/vm/_client_factory.py
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/sig/share/__cmd_group.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/sig/share/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/sig/share/_update.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_client_factory.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/custom.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/operations/sig_share.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_community_gallery_operations.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_disk_from_diff_gallery_image_version.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_shared_gallery.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_update_gallery_permissions.yaml
Labels: Compute, Auto-Assign

#30652 [Compute] `az vm list-sizes`: Remove unused parameter `--ids`
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2018_03_01_hybrid/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2018_03_01_hybrid/operations/vm.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2019_03_01_hybrid/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2019_03_01_hybrid/operations/vm.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2020_09_01_hybrid/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2020_09_01_hybrid/operations/vm.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/operations/vm.py
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2018_03_01/recordings/test_vm_size_list.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vm_size_list.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vm_size_list.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_size_list.yaml
Labels: Compute, Auto-Assign

#30309 [AKS] Add Etags in AKS CLI
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
  src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#30676 [Keyvault] `az keyvault update/update-hsm`: Fix `--bypass` overriding by default when specifying `--default-action Deny`
  src/azure-cli/azure/cli/command_modules/keyvault/custom.py
Labels: KeyVault, Auto-Assign

#30593 [Role] Add `az role definition show` command
  src/azure-cli/azure/cli/command_modules/role/_help.py
  src/azure-cli/azure/cli/command_modules/role/_params.py
  src/azure-cli/azure/cli/command_modules/role/commands.py
  src/azure-cli/azure/cli/command_modules/role/custom.py
  src/azure-cli/azure/cli/command_modules/role/tests/latest/recordings/test_built_in_role_definition_scenario.yaml
  src/azure-cli/azure/cli/command_modules/role/tests/latest/test_role.py
Labels: RBAC, Auto-Assign

#30639 [Network] `az network lb create`: Refine `--frontend-ip-zone` to support multiple zones
  src/azure-cli/azure/cli/command_modules/network/_params.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_lb_frontend_ip_zone.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#30679 {RDBMS} az postgres flexible-server identity update/assign: modify the logic for flexible_server_identity_update and flexible_server_identity_assign
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_fabric_mirroring_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgresql_flexible_server_identity_aad_admin_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgresql_flexible_server_identity_aad_admin_only_mgmt.yaml
Labels: Auto-Assign

#30643 {Packaging} Accelerate command execution in Docker image with warm start
  azure-linux.dockerfile
Labels: Packaging, Auto-Assign

#30687 {RDBMS} `az postgres flexible-server backup create`: add backup name validator
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#30685 {RDBMS} `az postgres flexible-server identity remove/update`: modify the logic for flexible_server_identity_remove, edit the error text for flexible_server_identity_update
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
Labels: Auto-Assign

#30525 [Profile] `az login`: Add `--client-id`, `--object-id` and `--resource-id` for authenticating with user-assigned managed identity
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/tests/test_profile.py
  src/azure-cli/azure/cli/command_modules/profile/__init__.py
  src/azure-cli/azure/cli/command_modules/profile/_help.py
  src/azure-cli/azure/cli/command_modules/profile/custom.py
  src/azure-cli/azure/cli/command_modules/profile/tests/latest/test_profile_custom.py
Labels: Account, Auto-Assign

#30692 [Compute] `az vmss create/update`: Add new paramter `--zone-balance` to support setting zone balance
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_zone_balance.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#30689 [RDBMS] `az postgres flexible-server geo-restore`: add optional `--restore-time` parameter
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#30636 [App Service] `az functionapp create`: Refactor EOL implementation and sort based on runtime EOL date
  src/azure-cli/azure/cli/command_modules/appservice/_constants.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add_ip_address_validation.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add_scm.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_remove.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_remove_scm.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_set_complex.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_set_simple.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_show.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_assign_user_identity.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_config_with_appcontainer_managed_environment_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_linux_powershell.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_ragrs_storage_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_container_config_set_replicas.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_cors.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_default_rg_and_workspace.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_appcontainer_managed_environment.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_appcontainer_managed_environment_add_vnet_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_appcontainer_managed_environment_existing_app_insights.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_appcontainer_managed_environment_list_vnet_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_appcontainer_managed_environment_remove_vnet_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_replicas.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_delete_functions.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_enable_dapr.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_existing_default_rg.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_existing_workspace.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_https_only.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_keys_delete.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_keys_list.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_keys_set.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_keys_set_slot.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_local_context.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_powershell.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_powershell_with_runtime_version.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_dotnet_consumption.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_powershell_version.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_remove_identity.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_reserved_instance.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnetE2E.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_EP_sku_E2E.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_basic_sku_E2E.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_duplicate_name.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_vnet_integration_consumption_plan.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_powershell.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_without_runtime.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_app_insights_conn_string.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_app_insights_key.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_default_app_insights.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_with_no_default_app_insights.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_move_plan_to_elastic.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_access_restriction_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: Functions, Auto-Assign

#30688 [RDBMS] `az postgres flexible-server fabric-mirroring start/stop/update-databases`: Disable fabric mirroring on HA server
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_fabric_mirroring_mgmt.yaml
Labels: Auto-Assign

#30542 {ACR} Fix #30041: `az acr`: Fix the "multiple values for keyword argument" error when the acr commands running on SAW
  src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
Labels: Container Registry, Auto-Assign

#30669 {RDBMS} Update Python SDK for PostgreSQL flexible servers
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Auto-Assign

#30690 [Compute] `az vm/vmss create`: Install guest attestation extension when security type set to ConfidentialVM
  src/azure-cli/azure/cli/command_modules/vm/custom.py
Labels: Compute, Installation, Auto-Assign

#30628 [App Service] `az functionapp deployment slot create`: Add `--https-only` parameter for slot creation command
  src/azure-cli/azure/cli/command_modules/appservice/_params.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_default_true.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_false.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_true.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Labels: Functions, Auto-Assign

#30704 [Compute] `az vmss scale`: Add new logic to support scaling VMSS in edge zone
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_scale_extended_location.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#30673 [AppService] `az webapp list-runtimes`: Remove the JBoss '_byol' entries from the output for webapps with Linux OS
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
Labels: Web Apps, customer-reported, Auto-Assign

#30702 [Network] `az network routeserver create/update`: Add `--auto-scale-config`
  src/azure-cli/azure/cli/command_modules/network/_help.py
  src/azure-cli/azure/cli/command_modules/network/_params.py
  src/azure-cli/azure/cli/command_modules/network/_validators.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_create.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_list.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/routeserver/_update.py
  src/azure-cli/azure/cli/command_modules/network/custom.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_virtual_hub_router_scenario.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#30670 [Container app] Fix #28047: `az containerapp compose create`: Upgrade pycomposefile version to split environment variables on the first equal sign instead of every equal sign
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: customer-reported, Auto-Assign, ContainerApp

#30656 {AKS} `az aks approuting`: Fix short-summary typo
  src/azure-cli/azure/cli/command_modules/acs/_help.py
Labels: AKS, customer-reported, Auto-Assign

#30382 [ACR] `az acr manifest list-metadata`: Update help messages for untagged manifests
  src/azure-cli/azure/cli/command_modules/acr/_help.py
Labels: Container Registry, Auto-Assign

#30657 [Compute] Add Managed Identity Support in Azure Disk Encryption for VMSS
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/disk_encryption.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_disk_encryption_with_encryption_identity_e2e.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_disk_encryption_with_encryption_identity_not_acled_in_keyvaulte2e.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_disk_encryption_with_incorrect_encryption_identity_e2e.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_encryption_identity_for_disk_encryption.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_encryption_identity_set_at_encryption_cmdlet.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_incorrect_encryption_identity_for_disk_encryption.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_null_encryption_identity_for_disk_encryption.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#30706 {CI} Add git hook notice
  .github/template/git-hooks-note.md
  .github/workflows/GitHookNotice.yml
Labels: CI, Auto-Assign

#30531 [Backup] `az backup`: Add support for new AFS Vault Standard Policies
  src/azure-cli/azure/cli/command_modules/backup/_params.py
  src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
  src/azure-cli/azure/cli/command_modules/backup/custom_base.py
  src/azure-cli/azure/cli/command_modules/backup/custom_help.py
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/preparers.py
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_item.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_policy.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_vaultstandard_item.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_vaultstandard_policy.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_vaultstandard_rp.yaml
  src/azure-cli/azure/cli/command_modules/backup/tests/latest/test_afs_commands.py
Labels: Backup, Auto-Assign

#30334 {IoT} `az iot hub policy renew-key`: Service-side HIS renewal of IoT Hub policy keys
  src/azure-cli/azure/cli/command_modules/iot/custom.py
Labels: IoT, IoT/CLI, Auto-Assign

#30727 {Core} Bump MSAL to 1.31.2b1
  src/azure-cli-core/setup.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
Labels: Core, ARM, Auto-Assign

#30703 {core} Fixed generic update issue.
  src/azure-cli-core/azure/cli/core/commands/arm.py
  src/azure-cli-core/azure/cli/core/tests/test_util.py
  src/azure-cli-core/azure/cli/core/util.py
Labels: Core, Auto-Assign
