Repository Azure/azure-cli, pull requests merged in 2025-03, with the labels that each got.

#30916 {afd purge} Update example of purge command
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
Labels: customer-reported, Network - Front Door, Auto-Assign

#30912 {LTS} Backport #30759
  src/azure-cli/azure/cli/command_modules/eventgrid/custom.py
Labels: LTS

#30905 {LTS} Do not add `post` suffix for branches starting with `release`
  scripts/release/pypi/build.sh
Labels: LTS

#30900 {RDBMS} `az postgres flexible-server create/update`: change the error message for SKU name validator
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#30852 [Mysql] BREAKING CHANGE: `az mysql flexible-server create`: Change default values for `--auto-scale-iops`, `--version` for MySQL
  src/azure-cli/azure/cli/command_modules/mysql/_params.py
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/recordings/test_mysql_flexible_server_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/mysql/tests/latest/test_mysql_scenario.py
Labels: customer-reported, Auto-Assign

#30922 {CI} Increase pytest worker number
  scripts/release/debian/test_deb_package.py
  scripts/release/rpm/test_rpm_package.py
Labels: CI, Auto-Assign

#30841 [Role] `az role assignment list`: Include role assignments inherited from management groups
  src/azure-cli/azure/cli/command_modules/role/custom.py
Labels: RBAC, Auto-Assign

#29955 {Core} Decouple MSAL credentials from SDK `get_token` protocol
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/auth/constants.py
  src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py
  src/azure-cli-core/azure/cli/core/auth/identity.py
  src/azure-cli-core/azure/cli/core/auth/msal_credentials.py
  src/azure-cli-core/azure/cli/core/auth/util.py
  src/azure-cli-core/azure/cli/core/tests/test_profile.py
  src/azure-cli-testsdk/azure/cli/testsdk/patches.py
Labels: Core, Auto-Assign

#30952 {CI} Update GitHub workflows to use ubuntu-latest and add auto-assign labels for Quantum issues
  .github/policies/resourceManagement.yml
  .github/workflows/AddIssueComment.yml
  .github/workflows/AddIssueCommentWithLabel.yml
Labels: CI, Auto-Assign

#30934 {AFD} Fix `az afd rule condition list` example issue
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/rule/_list.py
Labels: Network - Front Door, Auto-Assign

#30894 {Compute} `az disk-encryption-set`: Migrate to AAZ
  src/azure-cli/azure/cli/command_modules/vm/_client_factory.py
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/_create.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/_delete.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/_list.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/_list_associated_resources.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/_show.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/_update.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk_encryption_set/_wait.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/disk_encryption_set/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/disk_encryption_set/_create.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/disk_encryption_set/_delete.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/disk_encryption_set/_list.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/disk_encryption_set/_show.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/disk_encryption_set/_update.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/disk_encryption_set/_wait.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_client_factory.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_params.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2020_09_01_hybrid/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2020_09_01_hybrid/operations/disk_encryption_set.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/operations/disk_encryption_set.py
  src/azure-cli/azure/cli/command_modules/vm/operations/disk_encryption_set_identity.py
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_disk_encryption_set.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/test_vm_commands.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_community_gallery_operations.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_confidential_disk_encryption_set.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_disk_from_diff_gallery_image_version.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_disk_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_identity.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_snapshot.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_application.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_e2e.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_image_version_with_target_extended_locations_encryption.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_os_disk_security_encryption.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_restore_point_encryption_local.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_restore_point_encryption_remote.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_shared_gallery.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_auto_shutdown.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#30857 [AKS] `az aks create/update`: Update recording rule group create logic for managed prometheus addon
  src/azure-cli/azure/cli/command_modules/acs/azuremonitormetrics/recordingrules/create.py
Labels: AKS, Auto-Assign

#30948 [RDBMS] `az postgres flexible-server update`: BUG FIX, Updating geo data encryption properties
  src/azure-cli/azure/cli/command_modules/rdbms/_flexible_server_util.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#30937 {Compute} `az vm application`: Migrate to Code Gen V2
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/_show.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/_update.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/commands.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/operations/vm.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_add_application.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_add_application_empty_version_ids.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_add_application_with_config_override.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_add_application_with_order_application.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#30970 {RDBMS} `az postgres flexible-server replica create`: Fix the issue with cross-server resource check
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
Labels: Auto-Assign

#30964 {Containerapp} Update code owner
  .github/CODEOWNERS
  src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_private_link_scope.py
Labels: Auto-Assign, ContainerApp

#30941 [Containerapp] Fix #30828: `az containerapp job stop`: Fix `TypeError` when `--job-execution-name` is not specified
  src/azure-cli/azure/cli/command_modules/containerapp/_clients.py
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerapp_job_executionstest_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_executions.py
Labels: Auto-Assign, ContainerApp

#30971 {RDBMS} `az postgres flexible-server identity update`: Cannot disable SAMI when Fabric Mirroring is enabled
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
Labels: Auto-Assign

#30924 [Network] `az network virtual-appliance`: Add command `get-boot-diagnostic-log` to support getting boot diagnostic logs
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/__init__.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/virtual_appliance/_get_boot_diagnostic_log.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_get_boot.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#30961 [Compute] `az disk`: Add new command `config update` to support updating disk size gb by PATCH method
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_update_patch.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/operations/disk.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_config_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#30927 {Storage} `az storage or-policy create/update`: or-policy metrics support tested
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_account_or_policy.yaml
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_account_scenarios.py
Labels: Storage, Auto-Assign

#30993 {Core} Bump `microsoft-security-utilities-secret-masker` to `1.0.0b4`
  src/azure-cli-core/azure/cli/core/tests/test_credential_helper.py
  src/azure-cli-core/setup.py
Labels: Core, Auto-Assign

#31000 [RDBMS] `az postgres flexible-server fabric-mirroring`: BUG FIX, Space separate list of databases was only picking up first name
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_fabric_mirroring_mgmt.yaml
Labels: Auto-Assign

#31016 {afd purge} Fix purge documentation
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
Labels: customer-reported, Network - Front Door, Auto-Assign

#30996 {CI} Update Azure Pipelines to use Ubuntu 22.04 pools
  .azure-pipelines/sync-alias.yml
  .azure-pipelines/templates/variables.yml
  azure-pipelines.yml
  scripts/live_test/CLITest.yml
Labels: CI, Auto-Assign

#31002 [Compute] `az vm/vmss create/update`: Add support for setting security type to `Standard`
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_template_builder.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_special_name.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_simple_orchestration_mode.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_security_type.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#31045 [Network] Fix #31003: `az network vpn-connection create`: Pass auxiliary authorization header for referenced resource IDs
  src/azure-cli/azure/cli/command_modules/network/custom.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_vpn_connection_aux.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#30977 [Compute] Fix #30976: `az sig image-version create`: Fix missing auxiliary tokens
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/sig/image_version/_create.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/sig/image_version/_update.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#31014 {Auth} Clarify `Identity` class's boundary
  src/azure-cli-core/azure/cli/core/auth/identity.py
Labels: Account, Auto-Assign

#31029 {Microsoft Entra ID} `az ad`: Ignore global `--subscription` in subgroups
  src/azure-cli/azure/cli/command_modules/role/_params.py
Labels: Graph, Auto-Assign

#31011 {CI} Use target_commitish branch in release to trigger Reference Docs CI
  .github/workflows/TriggerReferenceDocsCI.yml
Labels: CI, Auto-Assign

#31057 {Core} Fix #31047: Remove unnecessary field get in action retrieval
  src/azure-cli-core/azure/cli/core/breaking_change.py
Labels: Core, Auto-Assign

#31048 {Role} `az role assignment list`: Announce `--include-classic-administrators` deprecation breaking change
  src/azure-cli/azure/cli/command_modules/role/_breaking_change.py
  src/azure-cli/azure/cli/command_modules/role/_params.py
Labels: RBAC, Auto-Assign

#30928 {Auth} Support `get_token_info` protocol
  src/azure-cli-core/azure/cli/core/auth/credential_adaptor.py
  src/azure-cli-core/azure/cli/core/auth/msal_credentials.py
  src/azure-cli-core/azure/cli/core/auth/tests/test_credential_adaptor.py
  src/azure-cli-core/azure/cli/core/auth/util.py
Labels: Account, Auto-Assign

#31059 {CI} Update sync-alias.yml to push branch to azclibot/azure-cli repo
  .azure-pipelines/sync-alias.yml
Labels: CI, Auto-Assign

#30975 {Core} Extension Breaking Change Announcement Instruction
  doc/how_to_introduce_breaking_changes.md
  src/azure-cli-core/azure/cli/core/breaking_change.py
  src/azure-cli-core/azure/cli/core/tests/test_breaking_change.py
Labels: Core, Auto-Assign

#31062 [Backup] `az backup protection enable-for-vm`: Update in warning message while protecting Trusted Launch virtual machines
  src/azure-cli/azure/cli/command_modules/backup/custom.py
Labels: Backup, Auto-Assign

#31081 [Compute] Breaking changes pre-announcement
  src/azure-cli/azure/cli/command_modules/vm/_breaking_change.py
Labels: Compute, Auto-Assign

#31080 [Compute] `az vm list-sizes`: Mark the command as deprecated
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
Labels: Compute, Auto-Assign

#31079 {Storage} `az storage account migration start`: Add upcoming breaking change warning for confirmation
  src/azure-cli/azure/cli/command_modules/storage/_breaking_change.py
Labels: Storage, Auto-Assign

#31056 {AKS} `az aks create`: Add upcoming breaking change announcement
  src/azure-cli/azure/cli/command_modules/acs/_breaking_change.py
Labels: AKS, Auto-Assign

#31088 {Network} Support vpn gateway bandwidth
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_create.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_delete.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_list.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_show.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_update.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_wait.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_delete.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_list.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_show.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_update.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_wait.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_active_active_cross_premise_connection.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_active_active_vnet_connection.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_allow_traffic.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_edge_zone.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_ipsec.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_local_gateway.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_multi_auth.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_multi_auth1.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_nat_rule.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_nat_rule_sub_cmd.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_with_enable_private_ip_address.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering_sync.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_connection_ipsec.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_connection_nat_rule.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_aad.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_disconnect_connects.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_package_capture.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_sku.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_watcher_troubleshooting.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_vpn_client_package.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#31077 {Core} Migrate `empty_on_404` from track1 `CloudError` to track2 `HttpResponseError`
  src/azure-cli-core/azure/cli/core/util.py
Labels: Core, Auto-Assign

#31041 [ARM] Fix various issues with `az bicep`
  src/azure-cli/azure/cli/command_modules/resource/_bicep.py
  src/azure-cli/azure/cli/command_modules/resource/_bicep_config.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource_bicep.py
Labels: ARM, Auto-Assign

#31099 {Network} Revert vpn gateway bandwidth
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_create.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_delete.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_list.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_show.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_update.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_wait.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_delete.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_list.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_show.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_update.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vpn_connection/_wait.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_active_active_cross_premise_connection.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_active_active_vnet_connection.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_allow_traffic.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_edge_zone.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_ipsec.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_local_gateway.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_multi_auth.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_multi_auth1.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_nat_rule.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_nat_rule_sub_cmd.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_with_enable_private_ip_address.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_peering_sync.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_connection_ipsec.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_connection_nat_rule.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_aad.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_disconnect_connects.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_package_capture.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vpn_gateway_sku.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_watcher_troubleshooting.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_vpn_client_package.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: Network, Auto-Assign

#31074 [ARO] `az aro create`: Update VM SKU to align with best practices
  src/azure-cli/azure/cli/command_modules/aro/custom.py
Labels: customer-reported

#31083 [App Service] `az webapp deploy`: Warm-up kudu before making ARM deployment
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_create_function_app.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_deployment_function_app.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_acr_integration_function_app.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_domain_create.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add_ip_address_validation.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_add_scm.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_remove.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_remove_scm.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_set_complex.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_set_simple.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_access_restriction_show.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_consumption_ragrs_storage_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_default_true.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_false.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_slot_https_only_true.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_appcontainer_managed_environment_remove_vnet_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_appcontainer_managed_environment_vnet_config_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_min_replicas_error.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_create_with_replicas.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_delete_functions.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_e2e.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_https_only.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_powershell.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_linux_app_service_powershell_with_runtime_version.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_on_windows_app_service_dotnet_with_runtime_version.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_reserved_instance.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_update_slot.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_custom_handler.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_windows_runtime_functions_version.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_workloadprofiles.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_move_plan_to_elastic.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_sitecontainers_create_update_show_delete.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: Web Apps, customer-reported, Auto-Assign

#31094 {Packaging} Bump packaging to 24.2
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
Labels: Packaging, Auto-Assign

#31061 {Profile} `az login`: Announce `--username` breaking change for managed identity
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli/azure/cli/command_modules/profile/_breaking_change.py
  src/azure-cli/azure/cli/command_modules/profile/custom.py
Labels: Account, Auto-Assign

#31095 [AKS] `az aks create/update`: Add command to create/update a network isolated cluster
  src/azure-cli/azure/cli/command_modules/acs/_consts.py
  src/azure-cli/azure/cli/command_modules/acs/_help.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/_validators.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
  src/azure-cli/azure/cli/command_modules/acs/linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/recordings/test_aks_network_isolated_cluster.yaml
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#31050 [Storage] `az storage share/directory/file`: support NFS FileShares, add `az storage file hard-link create`
  src/azure-cli-core/azure/cli/core/profiles/_shared.py
  src/azure-cli/azure/cli/command_modules/storage/_help.py
  src/azure-cli/azure/cli/command_modules/storage/_params.py
  src/azure-cli/azure/cli/command_modules/storage/commands.py
  src/azure-cli/azure/cli/command_modules/storage/operations/file.py
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_share_nfs_scenario.yaml
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_scenarios.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: Storage, Auto-Assign

#30999 [RDBMS] `az postgres flexible-server create`: Bug fix, generating password when password auth is disabled. Support adding admin during create if Microsoft Entra is enabled.
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#31102 {MYSQL} Remove parameter restriction for `--high-availability` and add breaking change annoucement
  src/azure-cli/azure/cli/command_modules/mysql/_breaking_change.py
  src/azure-cli/azure/cli/command_modules/mysql/custom.py
Labels: customer-reported

#31111 {backup} Update paired region mapping config
  src/azure-cli/azure/cli/command_modules/backup/custom.py
Labels: Backup, Auto-Assign

#31006 [App Service] Fix: #27724: `az webapp config appsettings set`: Remove redaction warning message from output
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
Labels: Web Apps, Auto-Assign

#30986 [App Service] Fix #29512: `az webapp config backup update`: Fix `str` object has no attribute `name`
  src/azure-cli/azure/cli/command_modules/appservice/_params.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_backup_update.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: Web Apps, Backup, Auto-Assign

#30990 [App Service] Fix: #21721: `az webapp config storage-account add`: Add validation for non-existent FileShare
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_config.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: Web Apps, Auto-Assign

#31110 {afd} `az afd origin create` clean spam message, `az afd origin-group create` add `--enable-health-probe true`
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/endpoint/_purge.py
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin/_create.py
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/origin_group/_create.py
  src/azure-cli/azure/cli/command_modules/cdn/aaz/latest/afd/rule/_list.py
Labels: Network - Front Door, Auto-Assign

#31114 [Storage] `az storage share create`: Support `--enable-snapshot-virtual-directory-access`
  src/azure-cli/azure/cli/command_modules/storage/_params.py
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/recordings/test_storage_file_share_premium_scenario.yaml
  src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_file_share_scenarios.py
Labels: Storage, Auto-Assign

#31058 {Network} `az network vnet subnet`: Pre-announcement of `--default-outbound` removal
  src/azure-cli/azure/cli/command_modules/network/_breaking_change.py
Labels: Auto-Assign

#31019 [App Service] `az functionapp list-flexconsumption-locations`: Add `--details` and `--runtime` parameters to provide more details
  src/azure-cli/azure/cli/command_modules/appservice/_params.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Labels: Functions, Auto-Assign

#31112 {RDBMS} `az postgres flexible-server create, az postgres flexible-server update, az postgres flexible-server ad-admin`: Add upcoming breaking change announcements
  src/azure-cli/azure/cli/command_modules/rdbms/_breaking_change.py
  src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
  src/azure-cli/azure/cli/command_modules/rdbms/_params.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_commands.py
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgresql_flexible_server_identity_microsoft_entra_admin_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgresql_flexible_server_identity_microsoft_entra_admin_only_mgmt.yaml
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/test_rdbms_flexible_commands.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#31121 {ACR} `az acr login`: Add Upcoming Breaking Change Announcement
  src/azure-cli/azure/cli/command_modules/acr/_breaking_change.py
Labels: Container Registry, Auto-Assign

#31092 [Core] PREVIEW: Support MSAL managed identity
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/auth/msal_credentials.py
  src/azure-cli-core/azure/cli/core/tests/test_profile.py
Labels: Account, Core, Auto-Assign

#31123 {CI} Revert to Ubuntu 20.04 on ARM agent
  .azure-pipelines/templates/variables.yml
  azure-pipelines.yml
Labels: CI, Auto-Assign

#31122 {MYSQL} Revert the breaking change announcement in recently merged PR #31102
  src/azure-cli/azure/cli/command_modules/mysql/_breaking_change.py
Labels: customer-reported

#31124 {CI} Add exception in Credential Scanner
  scripts/ci/credscan/CredScanSuppressions.json
Labels: CI, Auto-Assign

#31103 {Core} Bump MSAL to 1.32.0
  src/azure-cli-core/setup.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
Labels: Account, Core, Auto-Assign

#30958 [App Service] Fix #20983: `az webapp config ssl import`: Make web app a non-required parameter
  src/azure-cli/azure/cli/command_modules/appservice/_help.py
  src/azure-cli/azure/cli/command_modules/appservice/_params.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_ssl_import_no_app.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py
Labels: Web Apps, Auto-Assign

#31010 {Compute} `az vm availability-set`: Migrate to AAZ
  src/azure-cli/azure/cli/command_modules/vm/_client_factory.py
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/_vm_utils.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/availability_set/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/availability_set/_delete.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/availability_set/_list.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/availability_set/_list_sizes.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/availability_set/_show.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vm/availability_set/_update.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2018_03_01_hybrid/vm/availability_set/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2018_03_01_hybrid/vm/availability_set/_delete.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2018_03_01_hybrid/vm/availability_set/_list.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2018_03_01_hybrid/vm/availability_set/_update.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2019_03_01_hybrid/vm/availability_set/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2019_03_01_hybrid/vm/availability_set/_delete.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2019_03_01_hybrid/vm/availability_set/_list.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2019_03_01_hybrid/vm/availability_set/_update.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/vm/availability_set/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/vm/availability_set/_list.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/profile_2020_09_01_hybrid/vm/availability_set/_update.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_client_factory.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_params.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/_vm_utils.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/custom.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2018_03_01_hybrid/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2018_03_01_hybrid/operations/vm_availability_set.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2019_03_01_hybrid/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2019_03_01_hybrid/operations/vm_availability_set.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2020_09_01_hybrid/commands.py
  src/azure-cli/azure/cli/command_modules/vm/azure_stack/profile_2020_09_01_hybrid/operations/vm_availability_set.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/operations/vm_availability_set.py
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2019_03_01/recordings/test_vm_availset.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/hybrid_2020_09_01/recordings/test_vm_availset.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_availset.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_existing_ids_options.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_create_existing_options.yaml
Labels: Compute, Auto-Assign

#31039 [ARO] `az aro update`: Fix update for clusters created with subnets that are now deleted
  src/azure-cli/azure/cli/command_modules/aro/custom.py
Labels: customer-reported, ARO, Auto-Assign

#31149 {RDBMS} `az postgres flexible-server update`: Cannot enable HA when Fabric Mirroring is enabled
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/tests/latest/recordings/test_postgres_flexible_server_mgmt_update_validator.yaml
Labels: Auto-Assign

#31159 {CI} Remove unused globals
  src/azure-cli/azure/cli/command_modules/network/azure_stack/zone_file/parse_zone_file.py
  src/azure-cli/azure/cli/command_modules/network/zone_file/parse_zone_file.py
Labels: CI, Auto-Assign
