Repository Azure/azure-cli, pull requests merged in 2025-08, with the labels that each got.

#31877 {AKS} Bump SDK to adopt singleapi
  src/azure-cli-core/azure/cli/core/profiles/_shared.py
  src/azure-cli/azure/cli/command_modules/acs/_completers.py
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/commands.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_agentpool_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_base_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_managed_cluster_decorator.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
  src/azure-cli/setup.py
Labels: AKS, Auto-Assign

#31896 [ARM] `az ts`: Capture subscription id from template resource id
  src/azure-cli/azure/cli/command_modules/resource/_client_factory.py
  src/azure-cli/azure/cli/command_modules/resource/custom.py
  src/azure-cli/azure/cli/command_modules/resource/tests/latest/test_resource.py
Labels: ARM

#31922 [AKS] `az aks create`: Change description for `--os-sku` parameter
  src/azure-cli/azure/cli/command_modules/acs/_help.py
Labels: AKS, Auto-Assign

#31906 [Container App] `az containerapp job update`: Fix `--min-executions` and `--max-executions` not accepting 0 values
  src/azure-cli/azure/cli/command_modules/containerapp/custom.py
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/recordings/test_containerappjob_update_min_max_executions_zero_e2e.yaml
  src/azure-cli/azure/cli/command_modules/containerapp/tests/latest/test_containerappjob_crud.py
Labels: Auto-Assign, ContainerApp

#31913 [IoT] BREAKING CHANGE: Migrate `az iot hub devicestream` command group to CLI extension
  src/azure-cli-core/azure/cli/core/profiles/_shared.py
  src/azure-cli/azure/cli/command_modules/iot/_help.py
  src/azure-cli/azure/cli/command_modules/iot/commands.py
  src/azure-cli/azure/cli/command_modules/iot/custom.py
  src/azure-cli/azure/cli/command_modules/iot/tests/latest/test_iot_commands.py
Labels: IoT, IoT/CLI, Auto-Assign

#31869 [Profile] `az account get-access-token`: Allow specifying `--tenant` with the current tenant
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/tests/test_profile.py
Labels: ARM, Auto-Assign

#31940 {CI} Fix cli login issue for regression test pipeline
  scripts/regression_test/extension_regression_test.yml
  scripts/regression_test/regression_test.yml
Labels: CI, Auto-Assign

#31856 [Profile] `az login`: Support `--claims-challenge` in device code flow
  src/azure-cli-core/azure/cli/core/_profile.py
  src/azure-cli-core/azure/cli/core/auth/identity.py
  src/azure-cli-core/setup.py
  src/azure-cli/requirements.py3.Darwin.txt
  src/azure-cli/requirements.py3.Linux.txt
  src/azure-cli/requirements.py3.windows.txt
Labels: Account, Auto-Assign

#31880 [App Service] `az webapp deploy`: Warm-up kudu using ARM warm-up API before making ARM deployment
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_one_deploy_scm.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_track_runtimestatus_buildfailed.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_track_runtimestatus_runtimefailed.yaml
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_track_runtimestatus_runtimesucessful.yaml
Labels: Web Apps, customer-reported, Auto-Assign

#31948 [RDBMS] `az postgres flexible-server create/update/restore`: Premium SSD V2 is no longer supported with Burstable compute tier
  src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py
  src/azure-cli/azure/cli/command_modules/rdbms/validators.py
Labels: Auto-Assign

#31865 [AppService] `az functionapp flex-migration`: Create commands to migrate CV1 apps to Flex
  src/azure-cli/azure/cli/command_modules/appservice/_help.py
  src/azure-cli/azure/cli/command_modules/appservice/_params.py
  src/azure-cli/azure/cli/command_modules/appservice/commands.py
  src/azure-cli/azure/cli/command_modules/appservice/custom.py
  src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_functionapp_commands.py
Labels: Functions, Auto-Assign

#31895 [Packaging] Support Python 3.13
  .azure-pipelines/breaking-change-tests.yml
  azure-pipelines-full-tests.yml
  azure-pipelines.yml
  doc/command_guidelines.md
  doc/extensions/authoring.md
  doc/install_linux_prerequisites.md
  scripts/ci/test_extensions.sh
  scripts/regression_test/regression_test.yml
  src/azure-cli-core/setup.py
  src/azure-cli-telemetry/setup.py
  src/azure-cli-testsdk/setup.py
  src/azure-cli/setup.py
Labels: Packaging, Auto-Assign

#31967 {CI} Disable `partnercenter` extension test
  scripts/ci/test_extensions.sh
Labels: CI, Auto-Assign

#31909 {Compute} `az vmss start`: Migrate to CodeGen based
  src/azure-cli/azure/cli/command_modules/vm/_help.py
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vmss/__init__.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/vmss/_start.py
  src/azure-cli/azure/cli/command_modules/vm/commands.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/operations/vmss.py
Labels: customer-reported

#31934 [Compute] `az disk create/grant-access`: Support Confidential VM OS Disks
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_create.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/disk/_grant_access.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_accelerated_network.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_architecture.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_completion_percent.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_confidential_disk_encryption_set.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption_pmk.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_bursting.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_config_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_data_access_auth_mode.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_encryption_set_disk_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_hibernation.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_snapshot_hyper_v_generation_default_to_null.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_trusted_launch.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_with_optimized_for_frequent_attach.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_performance_plus.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_public_network_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_restore_point_encryption_local.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_restore_point_encryption_remote.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_incremental.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_ultra_ssd.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_data_disk_creation_from_copy_and_restore.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_attach_from_copy_and_restore.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_with_standard_zrs_sku.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_zones.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_from_restore_point.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_logical_sector_size.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_storage_sku.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_upload.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_os_disk_swap.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_copy_start_detection.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_incremental.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_trusted_launch_os_disk_secure_upload.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_ultra_ssd_disk_update.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_ultra_ssd_storage_sku.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vmss_update_instance_disks.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#31966 [AKS] `az aks create/update`: Change `--enable-azure-container-storage` `--disable-azure-container-storage` behavior and add `--container-storage-version`
  linter_exclusions.yml
  src/azure-cli/azure/cli/command_modules/acs/_params.py
  src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_consts.py
  src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_helpers.py
  src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/_validators.py
  src/azure-cli/azure/cli/command_modules/acs/azurecontainerstorage/acstor_ops.py
  src/azure-cli/azure/cli/command_modules/acs/custom.py
  src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py
  src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_validators.py
Labels: Storage, AKS, Auto-Assign

#31984 [Network] `az network vnet-gateway`: Support VNET Gateway insights
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/__init__.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_get_resiliency_information.py
  src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/vnet_gateway/_get_routes_information.py
  src/azure-cli/azure/cli/command_modules/network/tests/latest/recordings/test_network_vnet_gateway_get_routes_and_resiliency_information.yaml
  src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
Labels: customer-reported, Auto-Assign

#31996 {CosmosDB} `az cosmosdb restore`: Fix test where a future time is incorrectly used
  src/azure-cli/azure/cli/command_modules/cosmosdb/tests/latest/test_cosmosdb_commands.py
Labels: CosmosDB, Auto-Assign

#31899 {AKS} `az aks enable-addons --addon monitoring`: handle existing linked resource in AMPLS gracefully
  src/azure-cli/azure/cli/command_modules/acs/addonconfiguration.py
Labels: AKS, Auto-Assign

#31998 [MySQL] `az mysql flexible-server upgrade`: Add new version 8.4
  src/azure-cli/azure/cli/command_modules/mysql/_params.py
  src/azure-cli/azure/cli/command_modules/mysql/custom.py
Labels: Auto-Assign

#31889 [Backup] `az backup restore restore-azurefileshare`: Fix a bug where the source storage account is deleted and the required sourceResourceId property is missing from the restore request payload
  src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
Labels: Backup, Auto-Assign

#31883 [Service Fabric] Fix #5338: `az sf cluster create`: Fix the bug where key-vault not placed in location specifed by `--location`
  src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
  src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_create_cluster_with_location_different_from_resource_group.yaml
  src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/test_sf_cluster.py
Labels: Service Fabric, Auto-Assign

#31816 [Service Fabric] Fix #5180: `az sf cluster create`: Change behavior to read cluster_name from parameters file if provided
  src/azure-cli/azure/cli/command_modules/servicefabric/custom.py
Labels: Service Fabric, Auto-Assign

#31891 [Compute] `az snapshot create`: Add new parameter `--instant-access-duration-minutes` to support creating instant access snapshot for premium SSD v2 and ultra disk
  src/azure-cli/azure/cli/command_modules/vm/_params.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/snapshot/_create.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/snapshot/_delete.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/snapshot/_list.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/snapshot/_show.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/snapshot/_update.py
  src/azure-cli/azure/cli/command_modules/vm/aaz/latest/snapshot/_wait.py
  src/azure-cli/azure/cli/command_modules/vm/custom.py
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_accelerated_network.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_architecture.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_completion_percent.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_create_image_version_with_region_cvm_encryption_pmk.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_snapshot_hyper_v_generation_default_to_null.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_disk_trusted_launch.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_image_version_vhd.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_gallery_specialized.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_public_network_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_incremental.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_snapshot_ultra_ssd.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_data_disk_creation_from_copy_and_restore.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_attach_from_copy_and_restore.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_create_with_standard_zrs_sku.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_disk_max_shares_etc.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_managed_disk.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_copy_start_detection.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_enable_instant_access.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/recordings/test_vm_snapshot_incremental.yaml
  src/azure-cli/azure/cli/command_modules/vm/tests/latest/test_vm_commands.py
Labels: Compute, Auto-Assign

#31994 {CI} Update SBOM task conditions to trigger on BatchedCI
  azure-pipelines.yml
Labels: CI, Auto-Assign

#31912 [Service Fabric] `az sf managed-application update`: Add breaking change pre-annoucement warnings for argument option removal
  src/azure-cli/azure/cli/command_modules/servicefabric/_breaking_change.py
Labels: Service Fabric, Auto-Assign

#31983 [SQL] `az sql server create`: Add `--tags` parameter to supply tags
  src/azure-cli/azure/cli/command_modules/sql/_help.py
  src/azure-cli/azure/cli/command_modules/sql/_params.py
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/recordings/test_sql_server_create_with_tags.yaml
  src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py
Labels: SQL, Auto-Assign
